### ISSUE TITLE
Support alternate config location as per XDG Base Directory Spec

### ISSUE THREAD

**Issue by audreyfeldroy** [cookiecutter/cookiecutter#104]
Suggested by @scanny:

> Might I suggest considering ~/.config/cookiecutter/config as a supported alternate location for the configuration file(s)? This is the location specified by the XDG Base Directory Specification (at least the ~/.config/ prefix is :).
> 
> I first came upon this location when GitHub for Mac put my .gitignore there as ~/.config/git/ignore. Git supports this location from I believe v1.7. I really like keeping as many as possible of my .dotfiles there now because it keeps my home directory more manageable; otherwise I'd have to scroll to see all the .xyz config files there.
> 
> I'm not sure if it would be the right place to place local templates or not. I suppose it depends on whether you consider those configuration or not. I personally wouldn't mind at all having them there, perhaps in ~/.config/cookiecutter/templates.

TODO: look at other examples of this.

**Comment by nfarrar** [comment]
This would be great. :) Cached cookiecutters in $XDG_CACHE_HOME/cookiecutter and user templates in $XDG_DATA_HOME/cookiecutter/templates. :)

**Comment by bersace** [comment]
I workaround this in my dotfiles to unclutter `~/`. https://github.com/bersace/dotfiles/commit/0bbcc2457b578aa9fde8593ca724442c2e7f27e3

That would be nice to support both rc location and move to cache home.

**Comment by scanny** [comment]
Nice workaround @bersace! I think I'll do it that way as well :)

**Comment by bersace** [comment]
@scanny you're welcome ! :)

**Comment by ssbarnea** [comment]
I am closing this because we have an updated version at https://github.com/cookiecutter/cookiecutter/pull/1355 which we will likely merge soon.

**Comment by HappyEinara** [comment]
NB the PR at #1355 seems to use XDG spec for the cache (working) files but does not address this specific issue: the use of `$XDG_CONFIG_HOME/cookiecutter/<some appropriate filename>`  as an alternative path to `~/.cookiecutterrc` in the config flow.

From the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

Looks like this could be done with a few elifs:

1. If `--default-config` is forced, no config file
2. If a file is specified on the commandline, use that.
3. If `$COOKIECUTTER_CONFIG` is set, use that.
4. if `$XDG_CONFIG_HOME` is set and `$XDG_CONFIG_HOME/cookiecutter/config` resolves to a file that exists, use that
5. If `$XDG_CONFIG_HOME` is unset and `~/.config/cookiecutter/config` exists, use that.
6. If `~/.cookiecutterrc` exists, use that.

The choice to prioritise the standardised location over the current hardcoded `~/.cookiecutterc` can be discussed. Note the nuance in 5.: we should fall back to `~/.config` only if `$XDG_CONFIG_HOME` is unset; if it's set but there's no `cookiecutter/config` in it, we should not attempt to look for `~/.config/cookiecutter/config`; that would be another nonstandard hardcoding.

My current approach is to put this in my dotfiles:
```
_config_base=${XDG_CONFIG_HOME:-$HOME/.config}                                               
_cookiecutter_config="$_config_base/cookiecutter/config"                                     
[[ -s "$_cookiecutter_config" ]] && export COOKIECUTTER_CONFIG="$_cookiecutter_config" 
```
I'm happy to put in a PR for XDG and config files specifically if you want and leave #1355 (XDG cache locations) alone, if you'd accept it and if you can tell me whether you agree standard locations should take precedence over `~/.cookiecutterrc`. As python <3.4 is unsupported by cookiecutter I'd also reimplement this with Pathlib over os.path if you agree.

**Comment by prof-milki** [comment]
There's a [workaround/patch in cookiedough](https://github.com/cookiecutter/cookiecutter/issues/1510) now, which overwrites cookiecutters config.py directly.

> Also settled on `~/.config//cookiecutter/config`.
>
>  * USER_CONFIG_PATH = `~/.config/cookiecutter/config`
>  * replay_dir = `~/.config/cookiecutter/replay/`
>  * cookiecutters_dir= `~/.cache/cookiecutters/`
>
> CD now [applies a **patch**](https://fossil.include-once.org/cookiedough/file/cookiedough/config.patch) directly onto the cookiecutter package:
>
>> ```diff
>> # api: patch
>> # description: apply onto .../site-packages/cookiecutter/ for xdg support
>> 
>> --- config.py   2021-03-22 14:55:25.449840370 +0100
>> +++ config.py   2021-03-22 15:00:20.738897569 +0100
>> @@ -10,6 +10,7 @@
>>  import collections
>>  
>>  import poyo
>> +import appdirs
>>  
>>  from cookiecutter.exceptions import ConfigDoesNotExistException
>>  from cookiecutter.exceptions import InvalidConfiguration
>> @@ -17,7 +18,7 @@
>>  
>>  logger = logging.getLogger(__name__)
>>  
>> -USER_CONFIG_PATH = os.path.expanduser('~/.cookiecutterrc')
>> +USER_CONFIG_PATH = appdirs.user_config_dir('cookiecutter', 'cookiecutter') + "/config"
>>  
>>  BUILTIN_ABBREVIATIONS = {
>>      'gh': 'https://github.com/{0}.git',
>> @@ -26,8 +27,8 @@
>>  }
>>  
>>  DEFAULT_CONFIG = {
>> -    'cookiecutters_dir': os.path.expanduser('~/.cookiecutters/'),
>> -    'replay_dir': os.path.expanduser('~/.cookiecutter_replay/'),
>> +    'cookiecutters_dir': appdirs.user_cache_dir("cookiecutters", "cookiecutters"),
>> +    'replay_dir': appdirs.user_config_dir('cookiecutter', 'cookiecutter') + "/replay/",
>>      'default_context': collections.OrderedDict([]),
>>      'abbreviations': BUILTIN_ABBREVIATIONS,
>>  }
>> ```

**Comment by HappyEinara** [comment]
> Also settled on ~/.config//cookiecutter/config.
> 
>     USER_CONFIG_PATH = ~/.config/cookiecutter/config
>     replay_dir = ~/.config/cookiecutter/replay/
>     cookiecutters_dir= ~/.cache/cookiecutters/

Just to clarify this snippet: the paths there are the _defaults_ should the user not have configured `$XDG_CONFIG_HOME` and/or `$XDG_CACHE_HOME`. Your implementation by way of `appdirs` is absolutely the correct implementation however and will respect those environment variables. Good stuff.

Would be nice to get this merged upstream into cookiecutter (with backwards compatible support for `~/.cookiecutterrc` if present).

**Comment by exhuma** [comment]
Is there any update on this? I see that @HappyEinara has offered to open a PR for this, I was about to do the same :) I agree with all the points mentioned in https://github.com/cookiecutter/cookiecutter/issues/104#issuecomment-798827971

Any plans on how this can move forward?

**Comment by HappyEinara** [comment]
@exhuma I won't get chance to do this any time soon, so don't hold off on my account (but maybe check on the Discord if the admins don't respond; this issue has been around for a while)

**Comment by ssbarnea** [comment]
One may want to also check https://dot-config.github.io/ for an even generic approach, which allows use inside project, not only user level config -- maybe an extrapolation of XDG applied to projects.

A personal note, I kinda find use of generic `config` files, without extension or a clear name as an anti-pattern, even if they are put inside folders with tool name. If you have `config` open in as a tab in your editor you will never know to what tool it refers too. Also editors fail to properly determine the file type when you do not use an extension, even failing to provide auto-complete and schema validation.

That is why I always recommend to be explicit and follow something like `{toolname}}.{{yml|ini|toml|json}}`.

**Comment by obvionaoe** [comment]
Any progress on this issue?

**Comment by kurtmckee** [comment]
@jensens @pydanny @ssbarnea This issue is 10 years old. I recommend closing the issue.

**Comment by obvionaoe** [comment]
I think this issue is still relevant
