### ISSUE TITLE
Create web UI tool for cookiecutter

### ISSUE THREAD

**Issue by patcon** [cookiecutter/cookiecutter#1067]
First off, I looooove cookiecutter! Thanks for creating it and working on it! :heart: 

This is a bit of a long-shot, but wasn't sure where else to leave this.

I work in a community where not everyone has command-line skills, but we're trying to encourage them to run projects on GitHub (often code-related, but sometimes just doc resources and websites).

It would be really amazing if there was a web service that allowed a user to auth their github account, and then point to a cookiecutter template, and complete a wizard that would then initiate a github repository for them. This feels like it would be suuuuuuper friendly for getting people started on github with some best-practices in place :)

tags: web app, webapp, interface, frontend, gui, ui, visual

**Comment by dasdachs** [comment]
@patcon you mean somethin like the web UI that [vue-cli](https://cli.vuejs.org/guide/creating-a-project.html#using-the-gui) offers?

**Comment by patcon** [comment]
Coming back to this after a looong time :)

It's not currently the right thing for our community's use-case -- helping less technical folks scaffold out from project templates and customize a bit (incl docs and suggested structures and github repo settings), but it definitely gives me language to search deeper! Thanks!

**Comment by samj1912** [comment]
started working on https://github.com/samj1912/web-cc - which is sort of CC as a service via a web UI.

**Comment by samj1912** [comment]
Update: Done with the first draft - here is a demo!

![cookiecutter.gif](https://user-images.githubusercontent.com/16130816/87260603-b3e78380-c4aa-11ea-8078-5c8750752d0e.gif)

Notice how it loadede the defaults from the .github repository of the user-specified org.

**Comment by samj1912** [comment]
Some more updates in case anyone is interested - The repository now works with personal repos as well and creates commits on your behalf.

See ![cc-demo](https://user-images.githubusercontent.com/16130816/87863998-37e1b580-c95a-11ea-8105-62099ace35ca.gif)

**Comment by regicsolutions** [comment]
> Some more updates in case anyone is interested - The repository now works with personal repos as well and creates commits on your behalf.
> 
> See ![cc-demo](https://user-images.githubusercontent.com/16130816/87864056-13d2a400-c95b-11ea-9452-9bc64f3d3a1a.gif)
> 
> 

Awesome work!! These features would be a great addition to [backstage](https://backstage.io/docs/features/software-templates/software-templates-index)

**Comment by Andrew-Chen-Wang** [comment]
It looks pretty good! Though I think there would be a greater incentive for this if cookiecutter was a js project that could be served on a CDN (i.e. no backend) so people can use cookiecutter without a python dependency.

**Comment by gsdatta** [comment]
_Note: Shameless plug_

@samj1912 your work on this awesome! I've been working on something very similar to your tool (https://www.getcortexapp.com/products/service-creation) and just came across this thread! 

The approach we took: we hook into github/bitbucket/gitlab APIs to fetch the `cookiecutter.json` file on template load, and then translate that into a form view. It then runs `cookiecutter` under the hood, creates the repo and pushes the code there.

**Comment by insspb** [comment]
This should be project in outside field, we cannot handle it inside main project. Closing this

**Comment by jensens** [comment]
That said, it can be done under the umbrella of the GitHub organisation cookiecutter, but as a separate repository.
