### ISSUE TITLE
Creating an hosted version

### ISSUE THREAD

**Issue by jibaku** [cookiecutter/cookiecutter#1070]
Hello,  I would like to have an hosted version of cookiecutter to be able to create project without any access to a CLI.

Do you know if someone already built it ? To avoid duplicated effort.

Or do you have some hints on what to avoid and what not to forget while creating it.

Thanks

**Comment by hackebrot** [comment]
Hi @jibaku! :wave:

It's a nice idea and we've talked about it before. I don't think anyone on the maintainers team has the bandwidth to maintain another free and open-source project **and** run and support a platform without [some real sponsorship](https://github.com/audreyr/cookiecutter/pull/848#issuecomment-259575460) 😐 

We have put in a lot of work into creating a user-friendly CLI:
- [several CLI flags](https://cookiecutter.readthedocs.io/en/latest/advanced/cli_options.html) to customize the project generation
- [templated default values](https://cookiecutter.readthedocs.io/en/latest/advanced/templates_in_context.html) which get updated based on user input
- [user config](https://cookiecutter.readthedocs.io/en/latest/advanced/user_config.html) with default values
- ...

So you would have to replicate that somehow? Other than that, I think it's worth pointing out that some cookiecutter templates use hooks to call external tools, for example to initialize a new git repository. So providing a ``tar.gz`` or ``zip`` archive containing the generated directories and files might not be enough. That's all I can think of off the top of my head 🤔
