### ISSUE TITLE
string argument expected, got 'NoneType'

### ISSUE THREAD

**Issue by JustinCata** [cookiecutter/cookiecutter#1078]
* Cookiecutter version: 
* Template project url:
* Python version: Python 3.5.5 
* Operating System: Windows 10

### Description:

I am trying to pip install cookiecutter

### What I've run:

```
pip install cookiecutter
```

`TypeError: string argument expected, got 'NoneType'`

**Comment by akshaybabloo** [comment]
Are you using Anaconda by any chance?

**Comment by insspb** [comment]
Not confirmed with current version.
