### ISSUE TITLE
Come up with a better way to represent the escaped {, {{, }, }}

### ISSUE THREAD

**Issue by audreyfeldroy** [cookiecutter/cookiecutter#11]
Escaping curly braces in Jinja2 is possible, but it looks awful:

```
{{ "{" }}
{{ "{{" }}
{{ "}" }}
{{ "}}" }}

{{ {{ url_for('home') }} }}

{% raw %}
<p>Go <a href="{{ url_for('home') }}">Home</a></p>
{% endraw %}
```

What about supporting something else, since this is a common task? Some possibilities:
### Option 1: Use a backslash, like `\{` and `\{\{`

Pro: simple, intuitive.
Con: what if you really want a backslash, like if you're templating Windows paths?
### Option 2: Precede brace with an unusual character, like `☃{` and `☃{☃{`

Unicode snowmen look kinda like curly braces. 

Pro: Avoids the con of option 1, since using this combination is rare. 
Con: Hard to type, and kind of weird.
### Option 3: Surround them with a character, like `_{_` and `_{{_`

Pro: Don't have to escape every single one, making it more readable.
Con: What if you really wanted to type `_{_`? Is that ever a common thing to type, in any popular framework?

**Comment by adeck** [comment]
I don't immensely care, but it's worth pointing out that a person can also change the default delimiters if it comes up often enough:

- http://jinja.pocoo.org/docs/dev/templates/
- https://gist.github.com/lost-theory/3925738

Or you could simply have `{{{` be interpreted as a single `{`, and `}}}` as a single `}`, although that'd probably mess with syntax highlighting.

**Comment by xaxxon** [comment]
I seem to be having trouble trying to figure out how to put a brace after a substitution.   I had "{{somestuff{}}} but I was getting "{somestuffSubstitutionHere}}" so then I tried {{somestuff{}} but that gave an error about an unmatched {

So how do you follow a substitution with a close brace?

**Comment by eddie-dunn** [comment]
For anyone else looking here I would recommend using [raw blocks](http://jinja.pocoo.org/docs/dev/templates/#escaping) when working with larger jinja blocks inside cookiecutter. 

E.g.:
```
{% raw -%}
{{ foo }} and {{ bar }}
...
{{ baz }}
{%- endraw %}
```
yields
```
{{ foo }} and {{ bar }}
...
{{ baz }}
```

It was useful for me when generating Ansible templates with cookiecutter.
