### ISSUE TITLE
How to use _variable in cookiecutter.json correctly?

### ISSUE THREAD

**Issue by timonbimon** [cookiecutter/cookiecutter#1115]
* Cookiecutter version:  1.6.0
* Python version: 2.7

I'm trying to prompt the user for his desired Python Version and then extract the major and minor version to be used in my cookiecutter template

My cookiecutter.json looks sth like this:

{
    "repo_name": "template",
    "description": "This is Luminovo's template repository.",
    "author_name": "Your Name",
    "author_email": "you@example.com",
    "python_version": ["3.7.0", "3.6.6", "3.5.6"],
    "_major_python_version": "{{ cookiecutter.python_version[0] }}",
    "_minor_python_version": "{{ cookiecutter.python_version[2] }}"
}

unfortunately the {{ cookiecutter.python_version[0] }} part does not work (when running cookiecutter and using {{ cookiecutter._major_python_version }} it gets replaced with "{{ cookiecutter.python_version[0] }}" - not with "3")

it does work when not using an underscore in cookiecutter.json, but then it prompts the user for the major_python_version (and uses "3") as the default.

sorry if this is a very basic question, but i could not find anything about this in the documentation ^^

**Comment by gordonwrigley** [comment]
_ seems to be intended for things internal to cookie cutter rather than hidden things, subsequently {{}} expansion is not performed on _ variables, you can see this here:
https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/prompt.py#L203

**Comment by ekor15** [comment]
Then how can we prevent prompting the user on transformations we do like project_slug below?
`{
  "project_name": "my-project",
  "git_project_name": "{{cookiecutter.project_name}}",
  "owner_name": "owner",
  "email": "e@mail.com",
  "project_slug": "{{ cookiecutter.project_name.lower().replace(' ', '_').replace('-', '_') }}"
}
`

**Comment by gordonwrigley** [comment]
Afaik CookieCutter has no support for internal unprompted things. For the project I'm working on we've dealt with this by handling prompting ourselves and then running CookieCutter in no input mode. We can do this because we are invoking CookieCutter from within our own CLI. Incidentally that CLI is implemented with "click" which provides quite nice helpers for prompting.

**Comment by ekor15** [comment]
It would really simplify things if we can have this behavior out of the box

**Comment by Chris-Fourie** [comment]
```
{
"repo_name": "template",
"description": "This is Luminovo's template repository.",
"author_name": "Your Name",
"author_email": "you@example.com",
"python_version": ["3.7.0", "3.6.6", "3.5.6"],
"major_python_version": ["{{ cookiecutter.python_version[0] }}"],
"minor_python_version": ["{{ cookiecutter.python_version[2] }}"]
}
```
not a great solution - but the quickest I found if you don't want anyone modifying those last two lines... 
Basically a list with only one option...

**Comment by czue** [comment]
In the [cookiecutter private variables documentation](https://cookiecutter.readthedocs.io/en/latest/advanced/private_variables.html#private-variables) they note that you can use a double underscore to have the variable rendered.

I think what you want to do is as simple as renaming `_minor_python_version` to `__minor_python_version`

**Comment by samj1912** [comment]
The docs are for an unreleased version of cookiecutter, although it has been merged to master, it has not been released on pypi.

**Comment by czue** [comment]
ah good to know, thanks! looking forward to the release

**Comment by emirot** [comment]
> In the [cookiecutter private variables documentation](https://cookiecutter.readthedocs.io/en/latest/advanced/private_variables.html#private-variables) they note that you can use a double underscore to have the variable rendered.
> 
> I think what you want to do is as simple as renaming `_minor_python_version` to `__minor_python_version`

I doesn't look to render for me on 1.7.2

**Comment by ws1088** [comment]
> The docs are for an unreleased version of cookiecutter, although it has been merged to master, it has not been released on pypi.

So it's like the documents are released, but not the software/code. Sad...

**Comment by prowler0305** [comment]
Yeah the latest version of the docs as of today is up to 2.0.2 but pypi only has up to 1.7.3. I mean a single newer release of documentation compared to what is release, but 3!!!

**Comment by mdcain84** [comment]
Version 2.1.1 was released to pip June 1st.

https://pypi.org/project/cookiecutter/

After upgrading my version double underscore is working for my project.
