### ISSUE TITLE
Deeper scoped/dotted variable names seems not to be supported (in cookiecutter.json)

### ISSUE THREAD

**Issue by jenisys** [cookiecutter/cookiecutter#112]
VERSION: 0.7.0 (from pypi)

When the "cookiecutter.json" files contains:

``` json
{
    "project": {
         "name": "xxx",
         "author": "alice"
    }
}
```

the questioning logic gets confused. It assumes that only "project" must be asked and provides the OrderedDict as default value instead of asking the corresponding dotted names, like:

``` console
project.name (default: xxx) ?
project.author (default: alice) ?
```

NOTE: 
This is no problem for Jinja which can handle this.
If (currently) only flat (:= undotted) placeholder names are supported, this should be at least described in the docs (sorry in advance, if I have overlooked it).

**Comment by kurtmckee** [comment]
@jensens @pydanny @ssbarnea This issue is 10 years old. I recommend closing the issue.
