### ISSUE TITLE
Migrate template changes

### ISSUE THREAD

**Issue by nalch** [cookiecutter/cookiecutter#1134]
### Description
Oftentimes many projects are instantiated using a given cookiecutter template. During the lifetime of the projects the template is updated and these changes should be migrated to all the instantiated projects.
Keeping up to date with versions and architecture changes is a good example (f.e. rename pep8 to pycodestyle/black in the template and all instantiated projects, etc.).

### Pull Request
PR: https://github.com/audreyr/cookiecutter/pull/1133
Documentation: https://github.com/audreyr/cookiecutter/pull/1133/commits/29f0ccb132031c10f697dd12ad031e38b5cadd09#diff-e1aabcf37538ff8605c16fc241e4dded

### Proposed implementation:
- given a commit in the template repository
- create a patchfile in the source repository (containing the placeholders)
- render the patchfile using the context
- apply the patchfile in the target directory (or save it for manual application)

### Example:
- Having created a python package: `cookiecutter https://github.com/audreyr/cookiecutter-pypackage.git`
- Bugfixes/Changes/Features are introduced in the template
- Migrate the changes: `cookiecutter cookiecutter-pypackage --replay --cookie-pick <commit hexsha>`

### Open points:
- Dependency on gitpython
The pull request currently uses gitpython, but it's entirely possible to write our own diff/apply functions in the vcs.py
- Dependency on git
Currently it only works with git repositories. We could probably use diff/patch as well, but I'm not sure, if that's a common use case.
- Getting the context
Reapplying the context for the cookie-pick is a bit cumbersome. It works well with the `--replay` flag, but it's not really the use case to only reiterate the last run. It's possible to save the context in a file and use it though for now. I presume, that we could save the initial context in the target folder, if prompted (something like `--preserve-context`), but I'll create a separate ticket for that.

**Comment by ssbarnea** [comment]
While I personally do not see this feature of much practical use because almost always the expanded template diverge considerably from the original moment, I will not refuse this feature. 

I would invite others to use thumbs up/down to vote about it and see if we can see trend. If there is enough buy-in for it. 

Most important, I do expect cores to vote on this because there are maintenance costs that come due to such feature, that requires a less than trivial number of lines of codes.

**Comment by nalch** [comment]
Closed in favour of the same functionality in #784 and #1173.
