### ISSUE TITLE
Broken README links

### ISSUE THREAD

**Issue by scholtes** [cookiecutter/cookiecutter#1141]
* Cookiecutter version: Commit 3bc7b98
* Template project url: N/A
* Python version: N/A
* Operating System: N/A

### Description:
Links to Python packaging course in documentation are broken:
https://courses.twoscoopspress.com/courses/creating-and-distributing-python-packages
https://courses.twoscoopspress.com/courses/creating-and-distributing-python-packages-es

### What I've run:

- Navigate to https://github.com/audreyr/cookiecutter
- Scroll down to "Support This Project"
- Click image links (including Spanish language link)

**Comment by scholtes** [comment]
Notice: not a duplicate of #939 or #1060 (different links)

**Comment by davebza** [comment]
Is this issue still open? I'll take care of it if it is!

**Comment by RogueRaider** [comment]
I checked the [website](https://www.twoscoopspress.com/) and it seems that these courses are no longer available.

Should these links be replaced with different content from twoscoopspress?

**Comment by cs464osu** [comment]
Does merging [this pull request](https://github.com/audreyr/cookiecutter/pull/1142) not fix the issue? The links used there appear to work.

**Comment by insspb** [comment]
Fixed with merge of #1142
