### ISSUE TITLE
Fail with gitolite repository

### ISSUE THREAD

**Issue by javiersanp** [cookiecutter/cookiecutter#1143]
* Cookiecutter version: 1.6.0
* Template project url: Any
* Python version: Any (tested in 3.7)
* Operating System: Any (testes in ubuntu 16.04 and w$ 10)

### Description:

You are running a gitolite in "gitserver" and have a repository "mytemplate". When you run this::

    cookiecutter git clone git@gitserver:mytemplate

You get this fail::

    A valid repository for "git@gitserver:mytemplate" could not be found in the following locations:
C:\Users\javier\.cookiecutters\git@gitserver:mytemplate

### What I've run:

```
$ cookiecutter -v --debug-file log.txt git@gitserver:mytemplate
DEBUG cookiecutter.config: config_path is /home/jsanchez/.cookiecutterrc
DEBUG cookiecutter.utils: Making sure path exists: /home/jsanchez/.cookiecutters/
DEBUG cookiecutter.vcs: repo_dir is /home/jsanchez/.cookiecutters/git@gitserver:mytemplate
Clonar en «mytemplate»...
X11 forwarding request failed on channel 0
remote: Counting objects: 142, done.
remote: Compressing objects: 100% (118/118), done.
remote: Total 142 (delta 14), reused 0 (delta 0)
Receiving objects: 100% (142/142), 91.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (14/14), done.
Comprobando la conectividad… hecho.
A valid repository for "git@gitserver:mytemplate" could not be found in the following locations:
/home/jsanchez/.cookiecutters/git@gitserver:mytemplate
```
The repository mytemplate is correctly cloned in ~/.cookiecutters/mytemplate::
```
$ ls ~/.cookiecutters/cmsc_tmpl_python/
bin           cookiecutter.json              docs     doit.cfg  LICENSE     poetry.lock     README.md  tests
CHANGELOG.md  {{cookiecutter.project_slug}}  dodo.py  hooks     mkdocs.yml  pyproject.toml  tasks.txt  tox.ini
```
But `repo_dir` points to `~/.cookiecutters/git@gitserver:mytemplate` which don't exists.

**Comment by hackebrot** [comment]
Hi @javiersanp! 👋 

Thank you for raising this issue. 🍪
