### ISSUE TITLE
Change the Jinja

### ISSUE THREAD

**Issue by pprados** [cookiecutter/cookiecutter#1165]
* Cookiecutter version: 1.6.0
* Template project url:
* Python version: 3.7
* Operating System: Linux

### Description:

I would like to set Jinja variable: trim_blocks and strip_blocks
How I can do that ?

**Comment by Sonacrystal** [comment]
Use the {% set %} template tag and then assign the value the same way you would in normal python code.

**Comment by pydanny** [comment]
Great response @sonacrystal!

**Comment by eugenkleinschmidt** [comment]
> Use the {% set %} template tag and then assign the value the same way you would in normal python code. 😄

Can you describe it in more detail? `{% set trim_blocks = True %}` at beginning of file do not work for me

**Comment by Stanislav-Sakharov** [comment]
> > Use the {% set %} template tag and then assign the value the same way you would in normal python code. 😄
> 
> Can you describe it in more detail? `{% set trim_blocks = True %}` at beginning of file do not work for me

I'm looking for the answer too. Did you find it out?
