### ISSUE TITLE
Add documentation for abbreviations configuration in user config + related tests

### ISSUE THREAD

**Issue by kidynamit** [cookiecutter/cookiecutter#1171]
* Cookiecutter version: 1.6.0
* Template project url: github.com/rehive/service-framework
* Python version: 3.5.7
* Operating System: Ubuntu 18.04

### Description:

Aliased SSH hostname are not resolved.

### What I've run:

```
> cookiecutter github:rehive/service-framework   
A valid repository for "github:rehive/service-framework" could not be found in the following locations:
github:rehive/service-framework
/home/user/.cookiecutters/github:rehive/service-framework
```

**Comment by insspb** [comment]
Hi @kidynamit thank you for comment, and sorry for long response. 
I wanted to explore whole project code to understand how this and other feature works, to be more correct in my answer for this and other bugs.

At the end of the day. This is not a bug.  As from cookiecutter documentation we do not know this abbreviations, we know only `gh` for github. but you can setup own user config and use any abbreviations you need. More info in docs:

https://cookiecutter.readthedocs.io/en/1.7.0/advanced/user_config.html#user-config-0-7-0

Closed.
