### ISSUE TITLE
Help maintaining Cookiecutter?

### ISSUE THREAD

**Issue by maxrodrigo** [cookiecutter/cookiecutter#1174]
It's been 5 months without any update. Is there any way we can help with the repo maintenance?
There's this issue from 2014, #190, asking for maintainers, maybe is a good starting point to define some commiter criteria?

**Comment by insspb** [comment]
just faced this project several days ago, when was working on ansible roles templates in molecule project. I agree that this project needs more maintainers and will be glad to join a team.

**Comment by insspb** [comment]
Maybe @audreyr, @pydanny, @michaeljoseph, @pfmoore, and @hackebrot will share their thoughts about it.

**Comment by pfmoore** [comment]
Sorry, I no longer work on this project.

**Comment by ssbarnea** [comment]
I use this project in https://github.com/ansible/molecule and I would like to revive it or we will be forced to move away from it or even fork it (which I hate).

**Comment by maxrodrigo** [comment]
Let's see if some of the maintainers have something to say. If not we can consider forking it.

**Comment by pydanny** [comment]
Myself and @hackebrot have permission from our respective companies (Mozilla and BriteCore) to dedicate paid time to work on this project. I had hoped to start work back on it in June, but a series of family emergencies blocked me from participating.

I plan to begin working on Cookiecutter in July.

**Comment by insspb** [comment]
@pydanny, what about my help and help of @ssbarnea. As I see it we have an interest in this project too, so it is a good chance to expand developers team. Why not?

**Comment by pydanny** [comment]
@insspb @ssbarnea I'm willing to entertain the idea!

Next week when I have bandwidth to do open source, we can discuss plans for triaging issues and PRs, your help would be invaluable there and that would give us an opportunity to work together. 😄 

Also, considering how frequently this tool is installed across many systems, we need to check your credentials before granting merge access. I'm not sure how to do that, although having someone from RedHat confirm you work there would probably do that.

**Comment by ssbarnea** [comment]
@pydanny Glad to hear that. There are multiple ways to verify, starting with email, freenode openstack channels (especially #openstack-infra #tripleo are another way). FYI, I am always online on #irc because is needed for my daily work, nicks `zbr` or `ssbarnea` (both are registered).

Regarding maintenance, usually I assume that no change would merge without at least two core reviews. On few less mainstream projects I used one-core but only for trivial/minor changes.

**Comment by decentral1se** [comment]
Big <3 for keeping the dream alive on this project :rocket:

**Comment by insspb** [comment]
@pydanny, @ssbarnea 
To contact me main methods are email, slack, and Skype. I can be on Freenode on request. 
I agree about pr merging after 2 core reviews, except PRs related to docs, typos, etc. No need to waste a lot of time on such things, it is more useful to update them frequently.

**Comment by insspb** [comment]
@pydanny Maybe we should make a meeting? How to catch you?

**Comment by pydanny** [comment]
This week is intense at work. I'm meeting with my boss tomorrow to get me time to at least talk to people.

**Comment by insspb** [comment]
Hi @pydanny. Will you able to talk this week?

**Comment by pydanny** [comment]
Yes I will. How about 9PM UTC on July 1?

@insspb @ssbarnea Is there a slack channel you hang out in? Or we could do Gitter. @hackebrot You want in on this discussion? I' thinking topics of discussion will include, but are not :

1) Moving this project to a GitHub org (a little more complicated than it seems)
2) Triaging issues and PRs
3) Revising the change management process
4) Should we plan for Cookiecutter 2 (drops Python 2.x support)?

**Comment by insspb** [comment]
@pydanny We with @ssbarnea from different occupations and not from the same organization, so we do not do anything together now, except writing in this thread and discussing this problem. 
9 PM UTC is midnight in my TZ, better to make meeting several hours earlier, if possible. 
I can join any slack/gitter/skype(preferred)/irc channel

**Comment by ssbarnea** [comment]
I am in UK so at 9PM is 10PM.,... i am usually outside the home-office but I will setup a reminder that time. Skype

1. Clearly an github org is better than individual. Unless someone knows another one, I propose https://github.com/pycontribs -- transfer can be done without loosing any ticket and even having users automatically redirected. At least two, preferably 3 people should be marked as repo owners, so we give project some maintenance-redundancy.
2. Triaging would be what I would focus on (no plans to do any new features myself, at least for now)
3. I vote for 2x cores requirement
4. I would not support dropping 2.7 support, at least not until next year.
5. N/A

**Comment by insspb** [comment]
@pydanny @ssbarnea So where we will meet? We with @ssbarnea already found each other in Skype, @pydanny can you join Skype?

**Comment by pydanny** [comment]
Alright, Audrey gave me ownership of the Cookiecutter GitHub org that she owned and approval to move Cookiecutter there. That was very nice of her and I've already made that happen. 

However, considering how @audreyr has been whitewashed from projects over the years, I'm going to insist she get oodles of permanent credit for the project in the README and other places. When I mentioned this to her, her response was to insist that @hackebrot also get tons of permanent credit.

Now that we're moved over, let's have our discussion in Skype. My account name there should be `pydanny`. I'll get on and see what happens.

**Comment by insspb** [comment]
@pydanny added your skype. Check it out.

**Comment by insspb** [comment]
As a result. We have had a meeting and make some near future plan of project maintenance. 
Now we are begging issues and PRs clean up as the first step.

**Comment by pydanny** [comment]
@insspb, @ssbarnea, and @luzfcb have been made Triagers for Cookiecutter.

@luzfcb is a long time contributor to various Cookiecutter projects, in fact based on his skills we hired him at my company.

**Comment by ssbarnea** [comment]
Apparently this did not help much in what really counts **making a release**. The last tag and release on https://pypi.org/project/cookiecutter/#history is **more than two years old**.

Someone need to make this release, even if the tag it as a pre-release one.

**Comment by insspb** [comment]
Agree. We cannot do releases or modify documentation, so all other work has almost no sense.

**Comment by pydanny** [comment]
@insspb Let me check your rights and ensure you have permission to make necessary changes.

**Comment by insspb** [comment]
@ssbarnea 
After some time I see no other options as change release sequence. 
Next alpha release will be today/tomorrow, when I will deal with strange appveyour behavior. 
This will include only current master in state as it is, and maybe some doc changes. I will not include any PRs that are not reviewed by several commiters, if it is not doc/test related (all not reviewed).
Then I will switch this project to new/old development model, that should introduce some breathe here.
More details in issue #1256
