### ISSUE TITLE
Convert README and other non-Sphinx docs to Markdown

### ISSUE THREAD

**Issue by pydanny** [cookiecutter/cookiecutter#1179]
* Cookiecutter version: All
* Template project url: n/a
* Python version: n/a
* Operating System: n/a

### Description:

While ReStructuredText is a lot more powerful, for the purposes of this project Markdown suffices. Furthermore, it is much easier to work in Markdown.

**Comment by wagnernegrao** [comment]
Hi, Can I take this?!

**Comment by wagnernegrao** [comment]
Hi Can I take this?

**Comment by bukandu1** [comment]
Referencing the issue #1179.

Would like to work on converting the README.rst file to Markdown.

**Comment by wagnernegrao** [comment]
Hi @bukandu1 , I'm working on converting of all files .srt, PR #1185, but can prioritize the converting the CONTRIBUTING.rst

**Comment by bukandu1** [comment]
Do you mind if I help out since it's been a few weeks? Or I can take on the README.rst since they are both larger files.

**Comment by wagnernegrao** [comment]
I've converted the readme.md and I'm finishing the history.rst file, but I would like your help to review everything that has already been done, what do you think?

**Comment by Zhenye-Na** [comment]
Is there anyone still working on this? 

@wagnernegrao Have you already made a PR successfully? Thanks ~

**Comment by wagnernegrao** [comment]
Hi @Zhenye-Na, i worked on this but i finished. My PR #1185 is under analysis.

**Comment by insspb** [comment]
PR #1185 looks almost finished. Several issues left.

**Comment by hackebrot** [comment]
Hey @insspb! 👋 

What's the status of this issue now that #1216 has landed? 📝

**Comment by insspb** [comment]
Enought for now. Other docs are not in main repo, so will be converted in future. Or will not be converted at all, as it is time losing issue.
