### ISSUE TITLE
readme badges system needs update

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1180]
* Cookiecutter version: All
* Template project url: n/a
* Python version: n/a
* Operating System: /na

### Description:

After project movement from Audrey's repository to cookiecutter org, we need to update all services that get data from repo to make CI/CD and code analysis. 

Currently already not working: 

- [ ] Code health badge (https://landscape.io)
- [ ] All CI/CD steps, as shown in #1181 
   - [ ] Travis
   - [ ] appveyor/pr 
   - [ ] codecov
   - [ ] readthedocs

**Comment by michaeljoseph** [comment]
I think Travis is 👌 now, just needs a README.md update from `audreyr/cookiecutter`

**Comment by michaeljoseph** [comment]
https://readthedocs.org/projects/cookiecutter/ needs to updated by @audreyr or @pydanny.
I've deleted the old service: https://github.com/cookiecutter/cookiecutter/settings/installations so we should be able to add a webhook and be 👌
