### ISSUE TITLE
proposal: replace template listing with a link to github topic

### ISSUE THREAD

**Issue by ssbarnea** [cookiecutter/cookiecutter#1182]
I would like to propose to remove the [a-pantry-full-of-cookiecutters](https://github.com/cookiecutter/cookiecutter/blob/master/README.rst#a-pantry-full-of-cookiecutters) section from `README.rst` with a simple link to https://github.com/topics/cookiecutter-template

There are few reasons which made me propose this:

* Never-ending source of PRs which can hardly be evaluated without being biased
* Even if a template is good today, it may become broken or unmaintained tomorrow
* Out current list of templates already contains many outdated ones
* There is risk that someone would use the feature to promote malicious templates, amost impossible to catch, especially as they could change the template after inclusion

Advantages for outsourcing it:
* Github has a powerful browser with filters and sorting
* People can evaluate how popular templates are based on their starts
* We can focus on more important PRs
* Nobody could say that we refused on template in favour of another
* 134 repositories are already using the **[cookiecutter-template](https://github.com/topics/cookiecutter-template)** topic

Disadvantages
* Template creators would need to use GitHub to host them or to mirror their repositories on GitHub, which is not really a bit deal, OpenStack does it anyway.

Please use up/down thumbs to vote on this, or add comments with more details. I only hope we do not plan to build a database to list them.

**Comment by insspb** [comment]
I checked around 30 PRs with links update today. And it is almost impossible to track the future or history of each template. This is true.
Not sure that completely drop this list is a good idea. But at least movement to separate doc with security notice required.

**Comment by michaeljoseph** [comment]
I think there's value in having a small set of curated templates in the README (and consequently the homepage of the docs) for new users.
I feel like these would ideally need to be verified by CI (and perhaps include some versioning?)

**Comment by DerThorsten** [comment]
An other Idea would be to only show template which have a CI with nightly builds in the readme.
The build status of the individual templates should be visible in the readme. If somethings keeps failing it is removed
