### ISSUE TITLE
 C++ cookie-cutter (https://github.com/DerThorsten/cpp_cookiecutter)

### ISSUE THREAD

**Issue by DerThorsten** [cookiecutter/cookiecutter#1186]
Hi I wrote a pretty nice modern C++ cookie-cutter (https://github.com/DerThorsten/cpp_cookiecutter) which also generated python bindings with pybind11, it uses a nice cmake build systems, comes with preconfigured continuous integration scripts (travis, circleci, and azure pipelines), the generation of the rendered project is also tested on continuous integration servers.

One might consider adding this C++ cookiecutter to the list of cookiecutters

**Comment by luzfcb** [comment]
@DerThorsten 

> One might consider adding this C++ cookiecutter to the list of cookiecutters

yes, please send the pull-request and add into the c++ section

**Comment by DerThorsten** [comment]
see https://github.com/cookiecutter/cookiecutter/pull/1187

**Comment by insspb** [comment]
@DerThorsten 
Thank you. Please look at my comment in PR.

**Comment by ssbarnea** [comment]
We are no longer maintaining a list of templates inside README file and instead we use github topics feature. Please read https://github.com/cookiecutter/cookiecutter#a-pantry-full-of-cookiecutters and add the needed topics to your repository and people will be able to find your template. The most important one is ``cookiecutter-template``.

We are also going to remove most of already listed templates from there, in order not avoid being biased.
