### ISSUE TITLE
overwrite_if_exists behaviour

### ISSUE THREAD

**Issue by etijskens** [cookiecutter/cookiecutter#1190]
* Cookiecutter version: latest 1.6
* Template project url:
* Python version: 3.7
* Operating System: macOS

### Description:

I would like to use Cookiecutter incrementally. E.g start with a simple package, add a module (and corresponding tests), or add a cli (and corresponding tests), or add a module that is generated from fortran code with f2py (and corresponding tests), add a module that is generated from C++ code (and corresponding tests), ... I am writing a different Cookiecutter template for each case. 
This requires writing to the same directory and consequently I must specify overwrite_if_exists=True, because otherwise Cookiecutter complains that the directory already exists. However, at the same time I want to avoid that pre-existing files are being overwritten due to a bad choice of names by the user. This goes unnoticed, obviously, with overwrite_if_exists=True. 
A feature that does not emit errors on existing directories, but only on existing files would help me out.

**Comment by kodaman2** [comment]
You might be able to add an alias to bash_profile with a function to do this module, testing and whatever you need.

cppmod "mymodule"

**Comment by etijskens** [comment]
Thanks,
In the mean time I worked my way around this. I generated the files to be added in a temporary directory and then check whether any pre-existing files are going to be overwritten. If not files are moved. This has the additional advantage that if files would be overwritten the original project is untouched.

Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 10 Jul 2019, at 07:04, Fernando B <notifications@github.com<mailto:notifications@github.com>> wrote:


You might be able to add an alias to bash_profile with a function to do this module, testing and whatever you need.

cppmod "mymodule"

**Comment by insspb** [comment]
This is a feature request. needs new label :)
