### ISSUE TITLE
Release version 1.7.0 to PyPI

### ISSUE THREAD

**Issue by hackebrot** [cookiecutter/cookiecutter#1194]
This is a meta issue for tracking all issues and pull requests that need to be merged before we cut a new release and publish to PyPI. @cookiecutter/cookiecutter-sentinel can you please add them to the [1.7.0 milestone](https://github.com/cookiecutter/cookiecutter/milestone/23)?

**Comment by insspb** [comment]
#1179 and related pr #1185 looks good and almost finished.

**Comment by insspb** [comment]
#1105 Ready for merge

**Comment by ssbarnea** [comment]
Please make a pre-release like `1.7.0a0` so we can test it downstream. I do have CI jobs that run daily that are testing pre-releases from upstream dependencies, so I can find breaking bugs before they are... released.

**Comment by insspb** [comment]
@ssbarnea 1.7.0 released to pip https://pypi.org/project/cookiecutter/
