### ISSUE TITLE
Python 3.7 support on PyPI?

### ISSUE THREAD

**Issue by evertrol** [cookiecutter/cookiecutter#1196]
I noticed the README tags at the top for PyPI and PyPI itself do not list Python 3.7 as a supported version. Yet `setup.py` includes 3.7, and I can install Cookiecutter just fine with `pip` from PyPI (and run it in a simple fashion).
This for MacOS and Linux.

Is this simply an overlooked update, or have I missed something?

**Comment by hackebrot** [comment]
Hi @evertrol! 👋 

The badges on the README pull information from PyPI and other systems, whereas the setup.py file here is the latest checked in source. While Python 3.7 landed here on GitHub, we have yet to release a new version to PyPI. Please see #1194 for more information. 🍪

**Comment by evertrol** [comment]
Thanks. I had noticed #1194, but since that was for 1.7.0, I skipped that, since this should also apply to 1.6.0.
To me, it would not seem necessary to release a new version of Cookiecutter to update PyPI with the current version, or have I missed something?

**Comment by hackebrot** [comment]
Updating information on PyPI requires uploading a new distribution with a new version identifier. 📦 

The 1.6.0 release doesn't have [python-requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) specified in the [package information](https://github.com/cookiecutter/cookiecutter/blob/1.6.0/setup.py), which means pip will be able to install it for Python 3.7. FWIW I'm not aware of Python 3.7 incompatible code in cookiecutter.

**Comment by evertrol** [comment]
Ah, yes, the new version identifier.
Thanks for the clarification on both questions!
I'll see 1.7.0 coming along (hopefully) shortly.
