### ISSUE TITLE
Remove dead projects from "Similar projects"

### ISSUE THREAD

**Issue by pydanny** [cookiecutter/cookiecutter#1204]
* Cookiecutter version: Any
* Python version: All
* Operating System: All

### Description:

The similar projects list has projects with dead links. Or in the case of Pyramid's pcreate, have been superseded by Cookiecutter. Remove them from the list.

**Comment by seanmavley** [comment]
I just checked all the links here: https://cookiecutter.readthedocs.io/en/latest/readme.html#similar-projects

All point to live pages. Pyramid's pcreate is still on the list though. Going ahead to remove the pcreate then.

**Comment by insspb** [comment]
Thank you for notice. It will be implemented in #1185 before the merge.
