### ISSUE TITLE
poll: what chat medium would you preffer for cookiecutter?

### ISSUE THREAD

**Issue by ssbarnea** [cookiecutter/cookiecutter#1219]
As cookiecutter had track of trying too many communication mediums but never settling for one, I am going to take another approach: lets see what people want to use, so we can make an informed decision. 

* Please use up/down thumbs on comments to vote for or against one. 
* Do not add new comments that duplicate existing options
* If you propose new medium, be sure that you mention only one per comment, otherwise voting would not make sense.

**Comment by ssbarnea** [comment]
**irc** - reasoning: most important python libraries like tox, pytest,... are also using it, makes sense to stick with other developers. Yes is inconvenient due to the fact it does not natively support history and offline retention of message but you could use a bouncer or a service like https://about.riot.im/ to connect to it, which will add the missing features.

**Comment by ssbarnea** [comment]
skype

**Comment by ssbarnea** [comment]
[gitter](https://gitter.im/audreyr/cookiecutter): was already used in the past.

**Comment by ssbarnea** [comment]
slack: we should all remember that requires registration and it has limited chat history.

**Comment by ssbarnea** [comment]
discord

**Comment by insspb** [comment]
Not fully correct answer. 
For code devs slack, as it has history, snippets etc. and security.
For general help - irc.

**Comment by insspb** [comment]
We are at slack: https://cookiecutter-project.slack.com/

**Comment by jakauppila** [comment]
@insspb Is there an invite link to the Slack?
