### ISSUE TITLE
If else in cookiecutter.json

### ISSUE THREAD

**Issue by iveeshal** [cookiecutter/cookiecutter#1230]
Is it possible to write conditional if else in a cookiecutter.json

eg.

  "deployment_in":["aws","gcp"],

if deployement_in aws
 do soemthing
else do something

also based on waht we select should show the remaining options to the user

**Comment by insspb** [comment]
It is impossible to do such hard things in the current implementation. All you can do is to use pre-post hooks to delete unneeded templates after all answers done. 
But maybe sometime in future...
Currently I am closing it, as it is question, not issue.
