### ISSUE TITLE
[Question] Cookiecutter template for CircleCI

### ISSUE THREAD

**Issue by neomatrix369** [cookiecutter/cookiecutter#1245]
* Cookiecutter version: n/a
* Template project url: one of these https://github.com/cookiecutter/cookiecutter#python
* Python version: n/a
* Operating System: n/a

### Description:

Really like the tool and the idea behind it, great to see it has taken off amazingly with so much usage all across GitHub and elsewhere.

Wish to generate a project using a python template that generates config for CircleCI instead of the default TravisCI.

I have raised an issue on StackOverflow explaining with details:
https://stackoverflow.com/questions/58312858/is-there-a-cookiecutter-fork-that-generates-a-project-template-for-circleci-ins

Would really appreciate any hints or tips on it - I heard there is some template of this sort out there.

### What I've run:

Nothing so far, still exploring my options

**Comment by pydanny** [comment]
This question is better asked in cookiecutter-pypackage. Another option is for you to fork the cookiecutter-pypackage project yourself and add the CircleCI configuration there.

**Comment by neomatrix369** [comment]
> cookiecutter-pypackage

Ok thanks for the response, I have also posted it on Stackoverflow and there is a reply now.

**Comment by neomatrix369** [comment]
Someone replied to me on [SO](https://stackoverflow.com/questions/58312858/is-there-a-cookiecutter-fork-that-generates-a-project-template-for-circleci-ins), with this link:
https://github.com/nolte/cookiecutter-circleci
