### ISSUE TITLE
Cannot find a way to let the user choose qualifiers in a setup.py

### ISSUE THREAD

**Issue by ksamuel** [cookiecutter/cookiecutter#1250]
* Cookiecutter version:1.6
* Template project url: any
* Python version: any
* Operating System: any

### Description:

I've been trying to provide a generic setup.py, which means letting the user select among the huge number of qualifiers from here: https://pypi.org/pypi?%3Aaction=list_classifiers

Is there a way to do that ? It's not clear from the documentation.

**Comment by insspb** [comment]
We do not have multi choose option now. 
So you can ask about each one and have a huge template :)
