### ISSUE TITLE
Documenting cookiecutter with sphinx can't handle environment variables in config file

### ISSUE THREAD

**Issue by Micromegass** [cookiecutter/cookiecutter#1251]
* Cookiecutter version:
* Template project url:
* Python version:3.6
* Operating System:Mac Os ()

### Description:
I am trying to get sphinx running to document my django project built with cookiecutter but it seems like sphinx has trouble reading the environment variables in the settings file. 
### What I've run:
When running ```make html``` sphinx gives me problems reading the config file. It says django.core.exceptions.ImproperlyConfigured: Set the USE_DOCKER environment variable

When not calling django.setup() it also throws me an error with my envs: django.core.exceptions.ImproperlyConfigured: Set the POSTGRES_DB environment variable When I hardcode them, the error goes on to complain about the next environment variable. I can't hardcode them all into the config file, that is not an option.

My environment variables are properly configured. When I print them out running my localhost they are there. It seems that somehow sphinx cannot process them. I am also using docker, so maybe that could interfere but I don't know.

My relevant sphinx settings 

```
sys.path.insert(0, os.path.abspath('..'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'config.settings.local'
```

Parts of my config
```
DATABASES = {
    # 'default': env.db('DATABASE_URL'),  # This was the default value, but modification below seemed necessary
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env("POSTGRES_DB"),
        'USER': env("POSTGRES_USER"),
        'PASSWORD': env("POSTGRES_PASSWORD"),
        'HOST': env("POSTGRES_HOST"),
        'PORT': env("POSTGRES_PORT"),
     }
}
DATABASES['default']['ATOMIC_REQUESTS'] = True


INTERNAL_IPS = ['127.0.0.1', '10.0.2.2']
if env('USE_DOCKER') == 'yes':
    import socket
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS += [ip[:-1] + '1' for ip in ips]

# django-extensions
# ------------------------------------------------------------------------------
# https://django-extensions.readthedocs.io/en/latest/installation_instructions.html#configuration
INSTALLED_APPS += ['django_extensions']  # noqa F405

```
I also asked on SO: https://stackoverflow.com/questions/58992192/

Thanks for any help! And thanks for Cookiecutter, it's fantastic!

**Comment by Micromegass** [comment]
I got it to work by installing make in my installing ```make``` in my docker image and building the doc while spinning up the container with ```docker-compose -f local.yml run django make -C ./docs html```. I think this should be documented somewhere though, because it is really hard to find any infos on it. For extended discussion see also: https://github.com/pydanny/cookiecutter-django/issues/1747

For more info see my exe

**Comment by insspb** [comment]
We are not cookiecutter-django
