### ISSUE TITLE
News. Development and release plan. 

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1256]
Two weeks ago I was given full permissions to this repository, as well as to readthedocs and pypy. 
I see that there is a very small interest in this project from developers, so several things will be changed soon. This is an announcement about these changes.

1. At the Sunday version `1.7.0` will be released to pypy. It will be the current master, with maybe some not-code related changes.
2. This will be the last release with full code reviews from several core committers. Just because it delays development.
3. The final release of `1.7.x` expected on December 31. Only bugfixes for  `1.7.0` will be reviews at this time. 

New year plan.

The history of this project shows two things.
1. It is self-full at this moment. I.e. it does the thing that supposes to do at this moment. All problems have some kinds of workarounds.
2. Waiting for a sponsor is non-effective.

So the decision:

Let's make something new. With honor and respect to the past.

1. From January 1st and later master branch will include new changes that can be non-compatible with the old version but should introduce new functions.
2. Fixes for the old version will be included in new releases of `1.7.x`, but only bugfixes for confirmed bugs will be included. All new development should be made in the new version `2.0.x`
3. Contributors list for versions 1.x and 2.x will be separated in the documentation.
4. Templates links will be removed from the main master page, as we cannot control templates live and security. I will try to create issue at every template branch, how to implement correct keywords for GitHub search.
5. Most of the issues and pull requests will be closed or merged to 2.0.0 without waiting for contributors. Only live work should be at issues/pr page.

Feel free to comment on this issue. Every thought will be included in the development plan.

**Comment by insspb** [comment]
* Tag for 1.8.0 for next version where some not deep changes will be made, with still support of Python 2.7 (not sure about 2.7)
* Tag 2.0.0 is wide list of improvements and changes, some will be moved to 1.9 or to 2.1... The goal to make releases more frequently. Not one time in several years :)

**Comment by ljvmiranda921** [comment]
Hello @insspb , should we expect a final release of 1.7.X today? 

Happy New Year and Happy Holidays!!

**Comment by insspb** [comment]
Hi @ljvmiranda921, an excuse for missed message, there was a lot of work right before NY (I had a release to production on Jan 7)
There was no significant bugs in 1.7.0 and significant changes, so it was released to pip at Dec without pre-release stage.

**Comment by insspb** [comment]
Version 1.7.1 released.
## 1.7.1 (2019-04-21)

This release was focused on internal code and CI/CD changes. During this release all code was verified to match pep8, pep257 and other code-styling guides.  
Project CI/CD was significantly changed, Windows platform checks based on Appveyor engine was replaced by GitHub actions tests. Appveyor was removed. Also our CI/CD was extended with Mac builds, to verify project builds on Apple devices.

Important Changes:

* Added: Added debug messages for get_user_config [@ssbarnea](https://github.com/ssbarnea) (#1357)
* Multiple templates per one repository feature added. [@RomHartmann](https://github.com/RomHartmann) (#1224, #1063)
* Update replay.py json.dump indent for easy viewing [@nicain](https://github.com/nicain) (#1293)
* 'future' library replaced with 'six' as a more lightweight python porting library [@asottile](https://github.com/asottile) (#941)
* Added extension: Slugify template filter [@ppanero](https://github.com/ppanero) (#1336)
* Added command line option: `--skip-if-file-exists`, allow to skip the existing files when doing `overwrite_if_exists`. [@chhsiao1981](https://github.com/chhsiao1981) (#1076)
* Some packages versions limited to be compatible with python2.7 and python 3.5 [@insspb](https://github.com/insspb) (#1349)

Internal CI/CD and tests changes:

* Coverage comment in future merge requests disabled [@ssbarnea](https://github.com/ssbarnea) (#1279)
* Fixed Python 3.8 travis tests and setup.py message [@insspb](https://github.com/insspb) (#1295, #1297)
* Travis builds extended with Windows setup for all supported python versions [@insspb](https://github.com/insspb) (#1300, #1301)
* Update .travis.yml to be compatible with latest travis cfg specs [@luzfcb](https://github.com/luzfcb) (#1346)
* Added new test to improve tests coverage [@amey589](https://github.com/amey589) (#1023)
* Added missed coverage lines highlight to pytest-coverage report [@insspb](https://github.com/insspb) (#1352)
* pytest-catchlog package removed from test_requirements, as now it is included in pytest [@insspb](https://github.com/insspb) (#1347)
* Fixed `cov-report` tox invocation environment [@insspb](https://github.com/insspb) (#1350)
* Added: Release drafter support and configuration to exclude changelog update work and focus on development [@ssbarnea](https://github.com/ssbarnea) [@insspb](https://github.com/insspb) (#1356, #1362)
* Added: CI/CD steps for Github actions to speedup CI/CD [@insspb](https://github.com/insspb) (#1360)
* Removed: Appveyor CI/CD completely removed [@insspb](https://github.com/insspb) [@ssbarnea](https://github.com/ssbarnea) [@insspb](https://github.com/insspb) (#1363, #1367)

Code style and docs changes:

* Added black formatting verification on lint stage + project files reformatting [@ssbarnea](https://github.com/ssbarnea) [@insspb](https://github.com/insspb) (#1368)
* Added pep257 docstring for tests/* files [@insspb](https://github.com/insspb) (#1369, #1370, #1371, #1372, #1373, #1374, #1375, #1376, #1377, #1378, #1380, #1381)
* Added pep257 docstring for tests/conftests.py [@kishan](https://github.com/kishan3) (#1272, #1263)
* Added pep257 docstring for tests/replay/conftest.py [@kishan](https://github.com/kishan3) (#1270, #1268)
* Added pep257 docstring for docs/__init__.py [@kishan](https://github.com/kishan3) (#1273, #1265)
* Added missing docstring headers to all files [@croesnick](https://github.com/croesnick) (#1269, #1283)
* Gitter links replaced by Slack in README [@browniebroke](https://github.com/browniebroke) (#1282)
* flake8-docstrings tests added to CI/CD [@ssbarnea](https://github.com/ssbarnea) (#1284)
* Activated pydocstyle rule: D401 - First line should be in imperative mood [@ssbarnea](https://github.com/ssbarnea) (#1285)
* Activated pydocstyle rule: D200 - One-line docstring should fit on one line with quotes [@ssbarnea](https://github.com/ssbarnea) (#1288)
* Activated pydocstyle rule: D202 - No blank lines allowed after function docstring [@ssbarnea](https://github.com/ssbarnea) (#1288)
* Activated pydocstyle rule: D205 - 1 blank line required between summary line and description [@ssbarnea](https://github.com/ssbarnea) (#1286, #1287)
* Activated pydocstyle rule: ABS101 [@ssbarnea](https://github.com/ssbarnea) (#1288)
* Replaced click documentation links to point to version 7 [@igorbasko01](https://github.com/igorbasko01) (#1303)
* Updated submodule link to latest version with documentation links fix [@DanBoothDev](https://github.com/DanBoothDev) (#1388)
* Fixed links in main README file. [@insspb](https://github.com/insspb) (#1342)
* Fix indentation of .cookiecutterrc in README.md [@mhsekhavat](https://github.com/mhsekhavat) (#1322)
* Changed format of loggers invocation [@insspb](https://github.com/insspb) (#1307)

**Comment by geerlingguy** [comment]
@insspb - It seems like some new build failures (I'm using `molecule`, `yamllint`, `ansible-lint`, and `docker`) might be related to the cookiecutter 1.7.1 release which was just published. I noticed on one of my Ansible role CI tests that there are some new dependency conflicts which seem to point back to cookiecutter; see https://travis-ci.org/github/geerlingguy/ansible-role-firewall/jobs/677505674#L336-L374

I may be wrong, but the little amount of tracing I did pointed back to here :/ — see related issue https://github.com/geerlingguy/ansible-role-firewall/issues/74

**Comment by geerlingguy** [comment]
It seems like it can be traced back to https://github.com/cookiecutter/cookiecutter/commit/b7fcff0d909569103e19bfe3419cea8c7d46c246#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by geerlingguy** [comment]
Cookiecutter dependency in molecule is constrained to `cookiecutter >= 1.6.0` (see https://github.com/ansible-community/molecule/blob/c65488c4acb61fe2628b7f32e70b13998957a131/setup.cfg#L77).

**Comment by geerlingguy** [comment]
Attempting to lock in 1.7.0 with `pip install cookiecutter==1.7.0` prior to installing molecule...

**Comment by insspb** [comment]
@geerlingguy Thank you for report. Please try 1.7.2, just released to pip.

**Comment by geerlingguy** [comment]
@insspb - It looks like that fixed it; thanks so much for a quick fix, my other Ansible CI builds that will run through the night are much happier now :)

**Comment by insspb** [comment]
@geerlingguy No problem, but I saw this accidentally. I checked for new bugs before sleep, but you answered in old topic :) Please create issue next time. Thank you.

**Comment by ssbarnea** [comment]
@geerlingguy @insspb Thanks!
