### ISSUE TITLE
Expected date for next release.

### ISSUE THREAD

**Issue by erikpetersen-wf** [cookiecutter/cookiecutter#1292]
Hi all,

Great work with cookiecutter.  Has benefitted me and my teams significantly over the years.

I was curious if there was a release being planned that would include https://github.com/cookiecutter/cookiecutter/pull/1224 ?

**Comment by insspb** [comment]
hi @erikpetersen-wf planned for next 72 hours.

**Comment by erikpetersen-wf** [comment]
@insspb Is there a new release?

**Comment by insspb** [comment]
@erikpetersen-wf just found this mention :)
Last release was in april and available in pypi
Currently significally changed cookiecutter available in master branch. It includes a lot of old pull requests with different features (Check commits, 1 PR 1 commit). And any thoughts about master, as well as tests are welcome.
