### ISSUE TITLE
Remove flake-black from pre-commit

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1305]
Black is black and after implementation can report its own changes. What for we need plugin before black implementation?

**Comment by kishan3** [comment]
@insspb Should it be done or it is still open for discussion?

**Comment by ssbarnea** [comment]
If I remember well, flake8-black change flake8 settings to make it black compatible but I think that at some point it will no longer be needed as I know that flake8 guys were working actively to achieve 100% compliance between the two. If this happened, ok to remove it.
