### ISSUE TITLE
Question: Global var or something for license headers?

### ISSUE THREAD

**Issue by esotericpig** [cookiecutter/cookiecutter#1319]
Sorry to post this here, but wasn't sure where to.

Based on the license, I'd like to add an appropriate license header to the top of each source file (recommended practice).

For example, GPL:

```Ruby
#--
# This file is part of {{cookiecutter.project_name}}.
# Copyright (c) 2020 {{cookiecutter.author}}
# 
# {{cookiecutter.project_name}} is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# ...
#++
```

I don't want to put a big if-statement at the top of each source file with every license. When adding more licenses in the future, that would also be tedious.

First, I thought I'd just add a `pre_gen_project.py` hook, something like this:

```Python
if '{{cookiecutter.license}}' == 'GPL':
  # Set it here with a heredoc string
  license_header = '...'

{%set cookiecutter.license_header = license_header }
```

But, this doesn't seem to be possible at all?

My current solution is to do this:

```JSON
{
  "license": ["LGPL-3.0-or-later","GPL-3.0-or-later","None"],
  
  "license_header": {
    "LGPL-3.0-or-later": "\n#--\n# This file is part of {{cookiecutter.project_name}}.\n# Copyright (c) 2020 {{cookiecutter.author}}\n# \n# {{cookiecutter.project_name}} is free software: you can redistribute it and/or modify\n# it under the terms of the GNU Lesser General Public License as published by\n# the Free Software Foundation, either version 3 of the License, or\n# (at your option) any later version.\n# \n# {{cookiecutter.project_name}} is distributed in the hope that it will be useful,\n# but WITHOUT ANY WARRANTY; without even the implied warranty of\n# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n# GNU Lesser General Public License for more details.\n# \n# You should have received a copy of the GNU Lesser General Public License\n# along with {{cookiecutter.project_name}}.  If not, see <https://www.gnu.org/licenses/>.\n#++",
    "GPL-3.0-or-later":  "\n#--\n# This file is part of {{cookiecutter.project_name}}.\n# Copyright (c) 2020 {{cookiecutter.author}}\n# \n# {{cookiecutter.project_name}} is free software: you can redistribute it and/or modify\n# it under the terms of the GNU General Public License as published by\n# the Free Software Foundation, either version 3 of the License, or\n# (at your option) any later version.\n# \n# {{cookiecutter.project_name}} is distributed in the hope that it will be useful,\n# but WITHOUT ANY WARRANTY; without even the implied warranty of\n# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n# GNU General Public License for more details.\n# \n# You should have received a copy of the GNU General Public License\n# along with {{cookiecutter.project_name}}.  If not, see <https://www.gnu.org/licenses/>.\n#++",
    "None": ""
  }
}
```

And then in all of my source files, I do this:
`{{cookiecutter.license_header[cookiecutter.license]}}`

This solution is fine, but it makes the JSON file look really ugly, and the entire license header is on one line, so hard for others to edit (if fork).

I feel like my hands are tied behind my back only being able to use JSON and Jinja, without the power of Python to set the variables in cookiecutter some way.

I guess another alternative is to do this at the top of every source file:
`# LICENSE HEADER`

And then in `post_gen_project.py`, I'd find & replace all instances of `# LICENSE HEADER` with the the license header based on `{{cookiercutter.license}}`, but then aren't I just doing what a templating engine should be doing?

Thanks

**Comment by jhermann** [comment]
See https://github.com/Springerle/py-generic-project/blob/master/hooks/post_gen_project.py

Example: https://github.com/Springerle/py-generic-project/blob/master/%7B%7Bcookiecutter.repo_name%7D%7D/setup.py#L21

**Comment by jhermann** [comment]
What could be done better is indeed adding the short and full license text to the context in a pre-gen hook. But I don't know if that is possible yet.

**Comment by esotericpig** [comment]
Doesn't seem possible (without a lot of effort, as in my previous comments) or like it will be added in the future. So I will use a different project generation app for now, so closing. Thanks though.

**Comment by jhermann** [comment]
"doing better" does not mean the above solution does not work, I use it for years now. All you do is setting the license moniker as a normal CC variable and the rest just happens.

**Comment by esotericpig** [comment]
> "doing better" does not mean the above solution does not work, I use it for years now. All you do is setting the license moniker as a normal CC variable and the rest just happens.

That's fine. I'm not dumping on the cookiecutter project or the the people and the hard work they have done. That's great.

However, you had to add about 185 lines of code to do this (and my solution also took a lot of work). There are other scaffolding projects that I've found that are more flexible and let me add a license header to all of the source files with just a few lines. I won't share those projects out of courtesy to this project.

For me, I just need a different tool at this time. No big deal :+1: 

cookiecutter and the developers have done a fantastic job!
