### ISSUE TITLE
Doc:  HelloCookieCutter1 has a hardcoded commit # pointing to an obsolete version. 

### ISSUE THREAD

**Issue by VinceGa** [cookiecutter/cookiecutter#1320]
* Cookiecutter version: Latest
* Template project url:
* Python version:
* Operating System:

### Description:

The target has fixed several issues in the recent commits. But Doc folder as a hardcoded link to their commit # 1e4c680, 

```

**Comment by DanBoothDev** [comment]
Submodule updated in pull request #1338
