### ISSUE TITLE
ModuleNotFoundError when running cookiecutter with pyenv on OSX

### ISSUE THREAD

**Issue by dkapitan** [cookiecutter/cookiecutter#1324]
* Cookiecutter version: 1.7.0
* Template project url: https://github.com/drivendata/cookiecutter-data-science.git
* Python version: 3.6
* Operating System: OSX

### Description:

Running
```
cookiecutter https://github.com/drivendata/cookiecutter-data-science.git
```
results in an error:
```
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 6, in <module>
    from cookiecutter.__main__ import main
ModuleNotFoundError: No module named 'cookiecutter'
```

I think this is related to the shebang in `/usr/local/bin/cookiecutter`. Replacing that with a more generic

```
#!/usr/bin/env python
```
solved the problem for me.

Would it make sense to make this change? Happy to submit a PR.

**Comment by DanBoothDev** [comment]
Hey @dkapitan,
It could be that your virtual env doesn't have the module, if you run `python setup.py develop` does that resolve your issue?

**Comment by dkapitan** [comment]
Hey @DanBoothDev,

Thanks for following up. Just tried to reproduce my error, but I can't 😄 . You may be right I was just mixing up my different environments. Closing the issue.
