### ISSUE TITLE
documentation - bad link

### ISSUE THREAD

**Issue by BrianCHIG** [cookiecutter/cookiecutter#1326]
on page:
https://cookiecutter.readthedocs.io/en/1.7.0/first_steps.html#id2

on the last line:
 ```make sure you look at the list of pre-defined cookiecutters first!```

The linked resource is a 404:

https://cookiecutter.readthedocs.io/en/latest/readme.html#categories-of-cookiecutters

**Comment by DanBoothDev** [comment]
Linked fixed by submodule in commit https://github.com/BruceEckel/HelloCookieCutter1/commit/239ea692896301eaa280dd407fdd4d5c55cf6998

Pull request #1338 updates the submodule
