### ISSUE TITLE
test_{cli_extra_context_invalid_format,should_raise_error_without_template_arg} fail with click 7.1.1

### ISSUE THREAD

**Issue by dvzrv** [cookiecutter/cookiecutter#1327]
* Cookiecutter version: 1.7.0
* Template project url: -
* Python version: 3.8.2
* Operating System: Arch Linux

### Description:

Hi! I'm packaging python-cookiecutter for Arch Linux.
After package build and before installation (that is still during packaging) I'm running `pytest -v`.
The tests `test_cli_extra_context_invalid_format` and `test_should_raise_error_without_template_arg` fail due to slight changes in the output formatting (in click I assume).

This can be fixed with:

```
diff -ruN a/tests/test_cli.py b/tests/test_cli.py
--- a/tests/test_cli.py	2019-12-21 19:29:52.000000000 +0100
+++ b/tests/test_cli.py	2020-03-14 11:53:20.505357215 +0100
@@ -390,7 +390,7 @@
         'ExtraContextWithNoEqualsSoInvalid',
     )
     assert result.exit_code == 2
-    assert 'Error: Invalid value for "[EXTRA_CONTEXT]..."' in result.output
+    assert "Error: Invalid value for '[EXTRA_CONTEXT]...'" in result.output
     assert 'should contain items of the form key=value' in result.output
 
 
diff -ruN a/tests/test_cookiecutter_invocation.py b/tests/test_cookiecutter_invocation.py
--- a/tests/test_cookiecutter_invocation.py	2019-12-21 19:29:52.000000000 +0100
+++ b/tests/test_cookiecutter_invocation.py	2020-03-14 11:52:17.332550458 +0100
@@ -23,7 +23,7 @@
         subprocess.check_call([sys.executable, '-m', 'cookiecutter.cli'])
 
     _, err = capfd.readouterr()
-    exp_message = 'Error: Missing argument "TEMPLATE".'
+    exp_message = "Error: Missing argument 'TEMPLATE'."
     assert exp_message in err
```

### What I've run:

```
python setup.py build
PYTHONPATH="build:${PYTHONPATH}"
pytest -v
```

[python-cookiecutter-1.7.0-build.log](https://github.com/cookiecutter/cookiecutter/files/4332617/python-cookiecutter-1.7.0-build.log)

**Comment by insspb** [comment]
Hi @dvzrv , can you test current master?

**Comment by dvzrv** [comment]
This works apparently! Just tested on the most recent commit (b7fcff0).

**Comment by insspb** [comment]
@dvzrv Hope works means that bug not exist, closing. Please recreate it if I am wrong.
Thank you for report anyway.
