### ISSUE TITLE
Add support for typed template variables

### ISSUE THREAD

**Issue by petri** [cookiecutter/cookiecutter#138]
Currently, all variables in cookiecutter JSON templates are treated as strings.

It would be very useful if other types could be used. My use cases would most benefit from boolean support (see also #126).

Typing would also nicely open the way for later adding support for validating the input.

**Comment by mlabbe** [comment]
This is important.  Having "y"|lower or "n"|lower when you mean "if thing" is way too verbose and error prone.  Jinja2 permits booleans; let's use them.

**Comment by hackebrot** [comment]
See #848

**Comment by kurtmckee** [comment]
@jensens @pydanny @ssbarnea This issue is 10 years old. I recommend closing the issue.
