### ISSUE TITLE
QUES: Does CC work with GitLab?

### ISSUE THREAD

**Issue by joehoeller** [cookiecutter/cookiecutter#1392]
Does CC work with GitLab?

**Comment by insspb** [comment]
@joehoeller CC is template engine. You can make template for whatever you want. 
Our main repository is hosted on github and we do not have gitlab mirror at this moment.

**Comment by michaeljoseph** [comment]
@joehoeller yes, cookiecutter supports git templates hosted on GitLab.
https://cookiecutter.readthedocs.io/en/1.7.2/usage.html#works-directly-with-git-and-hg-mercurial-repos-too
