### ISSUE TITLE
An error occurred while creating the template using cookiecutter

### ISSUE THREAD

**Issue by 17864219845** [cookiecutter/cookiecutter#1393]
I really hope you can help me
I searched a lot of relevant information, but I didn't find the answer
My git works
[root@bogon test]# /usr/local/python3/bin/cookiecutter https://github.com/pydanny/cookiecutter-django.git
You've downloaded /root/.cookiecutters/cookiecutter-django before. Is it okay to delete and re-download it? [yes]: no
Do you want to re-use the existing version? [yes]: yes
A valid repository for "https://github.com/pydanny/cookiecutter-django.git" could not be found in the following locations:
/root/.cookiecutters/cookiecutter-django

**Comment by seawolf42** [comment]
What is the output of `ls /root/.cookiecutters`?

**Comment by 17864219845** [comment]
![PG 9(@}5E$B65I}D`(DL_FA](https://user-images.githubusercontent.com/51106548/82332900-92bd6600-9a18-11ea-8ec5-ccf5ef89b301.png)

I'm sorry.I just saw the news

**Comment by seawolf42** [comment]
OK, it sounds like what's in the `.cookiecutters` folder isn't the right thing. You might look inside `/root/.cookiecutters/cookiecutter-django` to make sure it's a valid copy of the git repository.

Is there a particular reason you don't want to re-download the local cached copy? I would try that next and see if things work as expected before spending too much time untangling what's in this directory. If you want to keep the existing one:

```bash
$ cd /root/.cookiecutters
$ mv cookiecutter-django cookiecutter-django.bak
$ # ... then try to create from the cookiecutter like you described above ...
```

Once you've done that, you can compare the contents of the newly-created copy of cookiecutter-django with the one you moved to a `.bak` name and see if there's something fundamentally different between them.

**Comment by 17864219845** [comment]
I've been busy with something recently. I 'm sorry to hear from you now. Thank you for your answer. It' s very useful for me. Thank you very much.

**Comment by insspb** [comment]
@17864219845 Please reopen if not solved. With full instructions to reproduce. 

But as @seawolf42 said before you should try to re-download first.
