### ISSUE TITLE
Documentation 2.0: All tutorials should be combined to one menu

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1411]
All tutorials should be combined to one menu

**Comment by Bhupesh-V** [comment]
Can I take this one ?
Also all the tutorials need to be under a new `tutorials` folder right?

**Comment by insspb** [comment]
@Bhupesh-V Yes it is free task and we will be glad if you make some work with PR on it. 
About how to combine it is up to you on final format. There are 3-4 parts of documentation that can be considered as tutorials.

**Comment by Bhupesh-V** [comment]
> @Bhupesh-V Yes it is free task and we will be glad if you make some work with PR on it.
> About how to combine it is up to you on final format. There are 3-4 parts of documentation that can be considered as tutorials.

Ok thanks, I will come up with a Draft PR soon
