### ISSUE TITLE
How do I use Cookiecutter in Go? 

### ISSUE THREAD

**Issue by king-john** [cookiecutter/cookiecutter#1435]
* Cookiecutter version:
* Template project url:
* Python version:
* Operating System:

### Description:

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### What I've run:

```
// REPLACE ME: Paste a log of command(s) you ran and cookiecutter's output, tracebacks, etc, here
```

**Comment by pydanny** [comment]
1. Install Cookiecutter using python
2. Use Go's `exec` package to call Cookiecutter
