### ISSUE TITLE
Looking for cookiecutter consulting 

### ISSUE THREAD

**Issue by joehoeller** [cookiecutter/cookiecutter#1440]
I have a unique problem and am looking to pay someone from the cookiecutter team to screen share and consult on hangout.

**Comment by bittner** [comment]
Nothing is unique enough to be impossible to describe it in words. Why not give it a shot?

And then, there is still the Cookiecutter source code that you can turn to, as a source of truth. If you want to troubleshoot yourself.

**Comment by joehoeller** [comment]
Correction: There was and is, you’re also a bit late to the game as I made
a very complex install happen. Please reference this article:

https://medium.com/@jgefroh/toxic-developers-considered-harmful-f7ea1494d4c0

**Comment by ssbarnea** [comment]
Closing as this is not really a bug. Nice article btw, sadly I got my own share of these.

**Comment by joehoeller** [comment]
Thank you @sorin.
