### ISSUE TITLE
missing Ubuntu 20.04 focal apt release

### ISSUE THREAD

**Issue by azazdeaz** [cookiecutter/cookiecutter#1446]
Hi, not sure if this is the right place to report this but the `cookiecutter` package is not available in the ubuntu registry for the latest LTS: https://packages.ubuntu.com/search?keywords=cookiecutter

**Comment by pydanny** [comment]
Apologies, but outside of PyPI the Cookiecutter team isn't involved in specific packaging platform releases. Maybe ask in the packages ubuntu repo?
