### ISSUE TITLE
Bad versioning: 1.7.1 -> 1.8.0

### ISSUE THREAD

**Issue by darkclouder** [cookiecutter/cookiecutter#1451]
The option `--directory` is added in 1.7.1.
This breaks the major.minor.patch version style where new features should only be introduced at minor levels and existing features should only be altered at major level. This should be version 1.8.0.
It breaks the general assumption that the docs/features between patch versions do not change but only bugs are fixed.
Especially when specifying version ranges for dependencies, this leads to unexpected errors.

Compare:
1.7.0
https://github.com/cookiecutter/cookiecutter/blob/1.7.0/cookiecutter/cli.py#L91

vs.

1.7.1
https://github.com/cookiecutter/cookiecutter/blob/1.7.1/cookiecutter/cli.py#L62

**Comment by pydanny** [comment]
Agreed, it was a mistake. Thanks for pointing it out.

**Comment by znerd** [comment]
For context, the Semantic Versioning convention:
- https://semver.org/

This ticket can be closed, right? Or is any further action expected?

**Comment by SharpEdgeMarshall** [comment]
I'm gonna close this, from what I see we are not going to retire 1.7.1.
