### ISSUE TITLE
Support CodeCommit GRC

### ISSUE THREAD

**Issue by jabrennem** [cookiecutter/cookiecutter#1453]
* Cookiecutter version: 1.7.2
* Template project url:
* Python version: 3.8
* Operating System: Mac/Linux

### Description:

I am not sure if there is already a way to do this, but I am simply trying to run cookie cutter on a git repo of mine that is stored in AWS CodeCommit. 

```bash
pip install git-remote-codecommit
cookiecutter codecommit::{region}://cookiecutter-template-repo
```

### What I've run:

I have run this command as below.

```bash
$ cookiecutter -v codecommit::{region}://cookiecutter-template-repo
DEBUG cookiecutter.config: User config not found. Loading default config.
A valid repository for "codecommit::{region}://cookiecutter-template-repo" could not be found in the following locations:
codecommit::{region}://cookiecutter-template-repo
/Users/{user_name}/.cookiecutters/codecommit::{region}://cookiecutter-template-repo
```

I looked into some of the source code, and it looks like the REPO_REGEX variable in repository.py only supports git, https, etc. I added codecommit::{region} and I encountered `cookiecutter.exceptions.UnknownRepoType`. I figured I would pass this along.

**Comment by SharpEdgeMarshall** [comment]
May I ask you why you need to use `git-remote-codecommit` instead of a simple `git clone`?

**Comment by yuvaldolev** [comment]
Hi @jabrennem @meckhardt @SharpEdgeMarshall 

We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened your issue at: https://github.com/cookieninja-generator/cookieninja/issues/39

We're trying to bring the life back to this amazing project.
We are committed to addressing each issue in up to 1 week from the day it's opened.
We'd really like you to join the fork, star it and contribute to it!

Thank you :)

**Comment by kurtmckee** [comment]
I'm closing this ticket because users can interact with VCS systems outside of cookiecutter.
