### ISSUE TITLE
_copy_without_render error

### ISSUE THREAD

**Issue by peach-lasagna** [cookiecutter/cookiecutter#1454]
* Cookiecutter version: 1.7.2
* Template project url: https://github.com/peach-lasagna/cookie_classic
* Python version: 3.8
* Operating System: Windows 10

### Description:
I want to download my template with _copy_without_render, but i catch error 

### What I've run:

```
$ cookiecutter https://github.com/peach-lasagna/cookie_classic.git
```

```
Unable to create file '.github\workflows\main.yaml'
Error message: 'matrix' is undefined
Context: {
    "cookiecutter": {
        "_copy_without_render": [
            "{{ cookiecutter.project_name }}/.github/workflows/main.yaml"
        ],
    }
}
```

[full traceback](https://gist.github.com/peach-lasagna/01607fc9fa8919e7f77949ada5ea6725)

**Comment by cjolowicz** [comment]
Hi @peach-lasagna 

Files are matched relative to the template directory. You can fix this by omitting the top-level directory:

```json
{
    "cookiecutter": {
        "_copy_without_render": [
            ".github/workflows/main.yaml"
        ],
    }
}
```

Also note that Cookiecutter does not render template variables with a leading underscore, like `_copy_without_render`. So, in general, you would need to use a wildcard (`*`) for any templated filename.

**Comment by peach-lasagna** [comment]
Thx so much
