### ISSUE TITLE
Black errors when running on a project repo

### ISSUE THREAD

**Issue by jackiekazil** [cookiecutter/cookiecutter#1457]
* Cookiecutter version: cookiecutter==1.6.0
* Template project url: (private)
* Python version: 3.8.5
* Operating System: MacOSx

### Description:

I am trying to run black on my project, but getting errors due to the cookiecutter commands in the repo. 

```
error: cannot format /Users/jackie/Projects/code/cookiecutter-pyrd/{{cookiecutter.project_slug}}/setup.py: Cannot parse: 9:5:     {%- if cookiecutter.command_line_interface|lower == 'click' %}'Click>=7.0',{%- endif %}
error: cannot format /Users/jackie/Projects/code/cookiecutter-pyrd/{{cookiecutter.project_slug}}/tests/test_{{cookiecutter.project_slug}}.py: Cannot parse: 6:1: {%- if cookiecutter.command_line_interface|lower == 'click' %}
error: cannot format /Users/jackie/Projects/code/cookiecutter-pyrd/{{cookiecutter.project_slug}}/{{cookiecutter.project_slug}}/cli.py: Cannot parse: 3:1: {%- if cookiecutter.command_line_interface|lower == 'argparse' %}
Oh no! 💥 💔 💥
7 files left unchanged, 3 files failed to reformat.
```

### What I've run:

I have tried the `--exclude` flag, but it feels like there should be better way. That is just ignoring the problem.

**Comment by noone234** [comment]
[Black](https://github.com/psf/black) can format _pure_ Python code.

You are right, black does not understand cookiecutter's template syntax.

It may be a little too early in the process to run black. After running `cookiecutter` to create a new project, you can then run `black` _on that project_. Does that make sense?

I do something very similar with yapf, a different Python code formatter. If I see immediate format changes in a generated project, I sometimes apply those changes to the cookiecutter to save time in the future. Some people that use my cookiecutters like the initial project to be well-formatted.

Hope this helps.

**Comment by jackiekazil** [comment]
Thank you. This is helpful! I was wondering if I was missing something.
