### ISSUE TITLE
How to access the remote cookiecutter URL in hook

### ISSUE THREAD

**Issue by maricatovictor** [cookiecutter/cookiecutter#1463]
The question is essentially simple:

How can I check if the user has used the SSH or HTTP remote of the cookiecutter template?

I tried reading from `~/.cookiecutters/{my_cookiecutter}/.git/config` however it seems like this file is not created until the hook has ended.

**Comment by cjolowicz** [comment]
Hi @maricatovictor , the location of the template is available in your hook as `{{ cookiecutter._template }}`. For example, if your hook is a Python script, you could store the location in a variable like this for further inspection:

```python
#/usr/bin/env python
template = "{{ cookiecutter._template }}"
```

**Comment by maricatovictor** [comment]
It was exactly what I was looking for, thank you very much! :)
