### ISSUE TITLE
jinja2_git doesn't install automatically

### ISSUE THREAD

**Issue by codeman101** [cookiecutter/cookiecutter#1474]
* Cookiecutter version: 1.7.2
* Template project url:n/a (issue is with cookiecuter app itself not my specific cookiecutter template)
* Python version:3.8
* Operating System: Mac catalina

### Description:

I wanted to report the fact that the jinja2_git dependency doesn't automatically install. I had to install in manually to get cookiecutter to work.

### What I've run:

N/A I got to run to since I separate pip3 installed jinja_git and then all worked fine but obviously the install script for cookiecutter should've done it upon install fo cookiecutter.

**Comment by luzfcb** [comment]
@codeman101 the `cookiecutter` not depends of `jinja2_git`. Can you please, create a new virtualenv, and describe the step by step commands that you execute to install `cookiecutter` and get the error?

Remember, on OSX, before executing `cookiecutter`, you need first to install the OSX command-line tools to install the `git`.


Open a terminal and run

```bash
xcode-select --install
```

After, click on the `Install` button and `Accept` the license agreement. Depending on your internet connection speed, installation may take some time.

**Comment by codeman101** [comment]
@luzfcb  What do you mean? https://github.com/cookiecutter/cookiecutter/blob/master/cookiecutter/environment.py This file from the codebase imports jinja2. I guess the OSX version uses the git version of that dependency.

**Comment by dokempf** [comment]
>     * Template project url:n/a (issue is with cookiecuter app itself not my specific cookiecutter template)

I doubt this. The [`jinja-git` extension](https://github.com/wemake-services/jinja2-git) is not used in cookiecutter itself (the code you mentioned imports `jinja`, not `jinja_git`). Jinja-git is e.g. used by this template https://github.com/wemake-services/wemake-django-template , but its usage instruction explicitly ask you to install it manually.

**Comment by SharpEdgeMarshall** [comment]
I think we can close this cause it doesn't look like a bug.
