### ISSUE TITLE
Feature request: documentation for each user-requested parameter 

### ISSUE THREAD

**Issue by stefanoborini** [cookiecutter/cookiecutter#1488]
### Description:

When I invoke cookiecutter on a template, I am prompted to fill the various configurable options from the json file. However, to provide a reasonable explanation to what the user is supposed to enter, I can only use the name of the option, and its value. I would like to specify in the json file a textual, user directed string that informs the user of what that option does. This string will
be printed out at execution just before the input prompt.

This change requires a modification of the json that needs to be backward compatible. One option would be to do:

```
Current syntax, works as before:
{
   "level": "9001"
}

Extension:
{
    "level": {
        "default": "9001"
        "help": "Please enter the energy level, likely to be over 9000 for a super Sayan"
    }
}
```

**Comment by edesz** [comment]
Hi @stefanoborini , if you have simple inputs (no multiple-choice options), then [the discussion in this issue](https://github.com/cookiecutter/cookiecutter/issues/794#issuecomment-455642359) could be somewhat useful.

In `cookiecutter.json`, you could try something like this
```
{
    "level": "help: Please enter the energy level, likely to be over 9000 for a super Sayan...default=9001"
}
```
The prompt would be
```
level [help: Please enter the energy level, likely to be over 9000 for a super Sayan...default=9001]:
```

This is just a workaround.

**Comment by stefanoborini** [comment]
@edesz Yes. This issue is a duplicate of #794. Closing.
