### ISSUE TITLE
Use Null or a specific value as default based on previous response

### ISSUE THREAD

**Issue by askpatrickw** [cookiecutter/cookiecutter#1500]
### Description:

If your prompt's default is null, an entry from the user is required.
If Choice A is selected, I'd like the default to be mydefault
If Choice B is selected, I'd like user_name to work the same as full_name does in the example.

```json
{
    "pick_one": [
        "Choice A",
        "Choice B"
    ],
    "user_name": "{%- if cookiecutter.pick_one == 'Choice A' -%} mydefault {%- else -%}  null {%- endif -%}",
    "full_name": null
}
```

### What I've run:

So far, I've tried wrapping null in curly braces, added safe to it.
`{{ null }}` or `{{ null | safe }}` but I get an error that the variable cannot be rendered because 'null' is undefined.
In other attempts, I get the string "null" as a default instead of requiring the user to enter a value.

thanks so much!

**Comment by simobasso** [comment]
Hey @askpatrickw, if you need a falsify what about:

```
{
    "pick_one": [
        "Choice A",
        "Choice B"
    ],
    "user_name": "{%- if cookiecutter.pick_one == 'Choice A' -%} mydefault {%- endif -%}",
    "full_name": null
}
```
