### ISSUE TITLE
private rendered dict is still prompted

### ISSUE THREAD

**Issue by juhuebner** [cookiecutter/cookiecutter#1502]
* Cookiecutter version: 2.0.0 from commit 52dd18513bbab7f0fbfcb2938c9644d9092247cf
* Python version: py3.8.7
* Operating System: Win

### Description:
For the `cookiecutter.json` below the private, rendered dict `__module_names` is still prompted in the output (last line).

For private variables c.f. https://github.com/cookiecutter/cookiecutter/issues/1115#issuecomment-442522474

### What I've run:

**cookiecutter.json:**
```
{
    "project_name": "Project Name",
    "project_slug": "{{ cookiecutter.project_name|lower|replace(' ', '-') }}",
    "__package_name": "{{ cookiecutter.project_name|lower|replace(' ', '_') }}",

    "__module_names": {
        "within": "{{ cookiecutter.project_slug }}",
        "outside": "{{ cookiecutter.__package_name }}"
    }
}
```
**verbose output:**
```
$ cookiecutter .\cookiecutter-context-test\ -f -v

DEBUG cookiecutter.config: User config not found. Loading default config.
DEBUG cookiecutter.main: context_file is .\cookiecutter-context-test\cookiecutter.json
DEBUG cookiecutter.generate: Context generated is OrderedDict([('cookiecutter', OrderedDict([('project_name', 'Project Name'), ('project_slug', "{{ cookiecutter.project_name|lower|replace(' ', '-') }}"), ('__package_name', "{{ cookiecutter.project_name|lower|replace(' ', '_') }}"), ('__module_names', OrderedDict([('within', '{{ cookiecutter.project_slug }}'), ('outside', '{{ cookiecutter.__package_name }}')]))]))])
project_name [Project Name]: 
project_slug [project-name]: 
__module_names [default]:
```

**Comment by prof-milki** [comment]
I have a feeling this fixes the same issue I mentioned in #1510 

> ##### `main(no_input=True)` and unspecified vars
> 
> So the whole point of CD is to provide a GUI over CC, specifically the template variables. Which `main()` accepts as `extra_context={}` already. However it seems you can only have either. There will be extraneous prompts for `no_input=False`, which makes feeding in the variables a bit pointless.
>
> Is there a way to allow for only unspecified fields to get prompted?
> Or would injection via `default_config={default_context:…}` work?
