### ISSUE TITLE
How can I add descriptive text to the `cookiecutter.json` file?

### ISSUE THREAD

**Issue by lazarillo** [cookiecutter/cookiecutter#1506]
* Cookiecutter version:

Cookiecutter 1.7.2

* Python version:

Python 3.8.8

### Description:

I simply want to know how I can add more descriptive text to a `cookiecutter.json` file to help future users better understand how to use the template.

As a silly example, if my `cookiecutter.json` looks like this:

```
{
  "project_name": "Azure Data Science API",
  "short_description": "An easy Azure end-to-end data science resource and API deploy",
  "author_name": "Please enter your name",
  "repo_name": "{{ cookiecutter.project_name.lower().replace(' ', '_') }}",
  "azure_resource_group": "dsproj-dev-rg"
}
```

But, for instance, it is not clear from this *whether the `azure_resource_group` will be created or should already pre-exist*.  (A resource group in Azure is a "container for project resources".)

I cannot put any descriptive text in the variable name `azure_resource_group`, since that variable is later used, and it would be quite messy to have the description following the variable everywhere in the code.

I cannot put it in the default value, since the default value should be a value that is usable as is.  Therefore, in this case, it could not have spaces since spaces are not allowed in the names of Azure resource groups.

### Desired Interface

I would like to do something like this:

```
{
  "project_name": "Azure Data Science API",
  "short_description": "An easy Azure end-to-end data science resource and API deploy",
  "author_name": "Please enter your name",
  "repo_name": "{{ cookiecutter.project_name.lower().replace(' ', '_') }}",
  "azure_resource_group [Note: the resource group must have already been created; this cookiecutter template will not create any Azure resources for you.]": "dsproj-dev-rg"
}
```

and have that `[Note: this resource group...]` only show up as a description, but be copied neither to the variable name nor the default value.

Is this possible?  If not, is this reasonable enough that I could spend a few hours to implement it and make a PR?

**Comment by limdauto** [comment]
I don't think it's possible at the moment. See: https://github.com/cookiecutter/cookiecutter/issues/794

**Comment by lazarillo** [comment]
Thank you, @limdauto !  I did try to search for older possibilities, but did not use the right keywords, I suppose.

#794  looks like it might even be outdated now and superseded by #848  https://github.com/cookiecutter/cookiecutter/pull/848

I will close this as a duplicate.

**Comment by JohnScience** [comment]
What about using cookiecutter.toml?

`toml` files allow comments.
