### ISSUE TITLE
[Question] Updating cookiecutter input variables in hooks ?

### ISSUE THREAD

**Issue by emirot** [cookiecutter/cookiecutter#1507]
* Cookiecutter version:Cookiecutter 1.7.2 
* Template project url:
* Python version:  Python 3.9)
* Operating System: mac os mojave 10.14.6 

### Description:

So I've used hooks in order to do some input validation and it worked.
E.g: 

```
import sys

group_name = '{{ cookiecutter.group_name }}'
if '.' in group_name
  print("Group name is incorrect!")
  sys.exit(1)
```
However I would like to update that variable for the user instead of failing:
Something like so in the if block:
```
group_name.replace('.', '')
```

Otherwise is there a better way to that ? (Should I use hooks )?

**Comment by samj1912** [comment]
Yes - see https://github.com/samj1912/cookiecutter-advanced-demo

**Comment by simobasso** [comment]
@emirot can we close this issue?
