### ISSUE TITLE
Cookiecutter package not found when install on Ubuntu

### ISSUE THREAD

**Issue by gutakk** [cookiecutter/cookiecutter#1509]
* Operating System: ubuntu-latest on Github actions

### Description:
Tried to run `sudo apt-get install cookiecutter` on Github actions but this error is raised
```sh
E: Unable to locate package cookiecutter
Error: Process completed with exit code 100.
```
You guys can try to re-run the workflow that passed 7 days ago but today it failed.
https://github.com/nimblehq/gin-templates/actions

Not sure what I'm missing something
Thank you

**Comment by luzfcb** [comment]
@gutakk thanks for opening the issue but the Ubuntu package is not our initiative and is not maintained by us, I suggest contacting the maintainers of the Ubuntu package.

Anyway, it looks like Ubuntu decided to remove cookiecutter repositories after Ubuntu 18.04

https://packages.ubuntu.com/search?keywords=cookiecutter&searchon=names&suite=all&section=all



```bash
# create the directory where the python installer will create 
# the link to the python command-line tools
mkdir -p "${HOME}/.local/bin"

```
# Add to your .bashrc or .zprofile

export PY_USER_BIN=$(python3 -c 'import site; print(site.USER_BASE + "/bin")')
export PATH="${PY_USER_BIN}:$PATH"
```

```
# close the terminal and open it again and run
python3 -m pip install --user cookiecutter
```

Although I categorically avoid suggesting installing any python packages via pip on the python that comes with the operating system (because this has a good chance of going wrong and ending up breaking python packages installed via apt-get and consequently breaking your Linux)

Installing it directly on the system's python is still an option:

```
sudo -H python3 -m pip install cookiecutter
```

Note: Do not forget to use `-H` when using `pip` with `sudo`.
The `-H` argument causes sudo to change the `$HOME` variable to the specified user's user home, that is, in the case it is `/root/`

If you forget to put `-H`, you face permission problems when trying to install a new package, because pip ran as root, but the cache folder was still `$HOME/.cache/pip/` for the current user and not the root user.

**Comment by gutakk** [comment]
Really appreciated @luzfcb
