### ISSUE TITLE
License terms slightly modified

### ISSUE THREAD

**Issue by sdinot** [cookiecutter/cookiecutter#1511]
Dear maintainers,

I reviewed the license of Cookiecutter, advertised as BSD 3-Clause, and noticed a change in [line 16](https://github.com/cookiecutter/cookiecutter/blob/52dd18513bbab7f0fbfcb2938c9644d9092247cf/LICENSE#L16) that seems minor, but which I don't understand.

The original text of BSD 3-Clause license is:
> Neither the name of **the copyright holder** nor the names of its contributors

In the license of Cookiecutter, the text above was replaced by:
> Neither the name of **border** nor the names of its contributors

Could you clarify the meaning of this modification?

**Comment by michaeljoseph** [comment]
Well spotted @sdinot!  
Is this an @audreyfeldroy easter egg 🥚 🐰 ?

Seriously though, this looks like a consequence of using cookiecutter to generate itself: 
https://github.com/audreyfeldroy/cookiecutter-pypackage/pull/228

A PR to change this back to the boilerplate should be uncontroversial 👍 
cc: @ehiggs
