### ISSUE TITLE
Error reading yaml file using `poyo` - `ValueError: Parent of ChildMixin instance needs to be a Container.`

### ISSUE THREAD

**Issue by acturner** [cookiecutter/cookiecutter#1513]
* Cookiecutter version: 1.7.2
* Template project url: https://github.com/acturner/cookiecutter-value-error
* Python version: 3.8.9
* Operating System: macOS

### Description:

When using a nested configuration which includes a list (see the list of authors in [example template](https://github.com/acturner/cookiecutter-value-error)), we obtain an error from `poyo` simply trying to read the yaml file:

```
ValueError: Parent of ChildMixin instance needs to be a Container.
```

### What I've run:

1. `git clone https://github.com/acturner/cookiecutter-value-error`
3. `cookiecutter cookiecutter-value-error --config-file=cookiecutter-value-error/init.yaml --no-input`

**Comment by simobasso** [comment]
Hey @acturner, thanks for spotted out. Can you please check https://github.com/cookiecutter/cookiecutter/pull/1516 if fix your issue?

**Comment by acturner** [comment]
@simobasso #1516 does not fix this issue, unfortunately. The error comes from `poyo` and I don't know why (drop-in replacement of `pyyaml` for `poyo` here fixes the problem but I know we can't use `pyyaml`).

**Comment by simobasso** [comment]
hey, @acturner thanks for the follow-up.

Yes, #1516 doesn't fix this issue.

it seems we have a lot of duplicated issue of the same bug, I'll try to link all of this issue so we can track better how to solve the issue at the root.

**Comment by glumia** [comment]
I looked into it, it's a problem with poyo not being able to correctly parse the list in the yaml file. There's even an open issue for that (hackebrot/poyo#12) dating back to 2016.

+1 for switching to PyYAML, as @ samj1912 said in https://github.com/cookiecutter/cookiecutter/pull/1515#issuecomment-825285176 they now provide pre-compiled binaries for windows so cross-platform compatibility shouldn't be a problem anymore.

**Comment by glumia** [comment]
Fixed with https://github.com/cookiecutter/cookiecutter/pull/1489.
