### ISSUE TITLE
Key error when using nested configuration files.

### ISSUE THREAD

**Issue by acturner** [cookiecutter/cookiecutter#1514]
* Cookiecutter version: 1.7.2
* Template project url: https://github.com/acturner/cookiecutter-key-error
* Python version: 3.8.9
* Operating System: macOS

### Description:

When using a nested configuration file, we get a key error because the key can't be found in the default `cookiecutter.json` config file (even when it exists). I will open a pull request with a one-line change that doesn't require the key to exist in the `cookiecutter.json` config, but I don't know why the key doesn't exist in the default.

### What I've run:

1. `git clone https://github.com/acturner/cookiecutter-key-error`
2. `cookiecutter cookiecutter-key-error --config-file=cookiecutter-key-error/init.yaml --no-input`

**Comment by simobasso** [comment]
Hey @acturner, thanks for spotted out. Can you please check https://github.com/cookiecutter/cookiecutter/pull/1516 if fix your issue?

**Comment by acturner** [comment]
@simobasso #1516 does fix this issue.

**Comment by simobasso** [comment]
@acturner, thanks for the update; we should wait for a maintainer to merge #1516

**Comment by simobasso** [comment]
@acturner just merged https://github.com/cookiecutter/cookiecutter/pull/1516 👍  let me know!
