### ISSUE TITLE
CI Fails by coverage lowered after Travis stopped working

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [cookiecutter/cookiecutter#1520]
* Cookiecutter version: latest

### Description:

Tests on Windows triggers `onerror` on `rmtree` function from `utils.py` causing [force_delete](https://github.com/cookiecutter/cookiecutter/blob/master/cookiecutter/utils.py#L30) function to be called and covered.

Since Travis stopped working we are relying only on Github Actions report that is not combining coverage from Windows, this is lowering coverage making CI fails.

### Fix:
We should combine coverage from all OS also on Github Actions

**Comment by simobasso** [comment]
Well spotted @SharpEdgeMarshall!

What do you think about removing the coverage stage on GitHub action and including those steps in the main stage 1 per job as https://github.com/codecov/codecov-action#example-workflowyml-with-codecov-action?

@insspb sorry for bothering you, but do you have any insight on why we need Travis _and_ Actions?

Thanks for your time
