### ISSUE TITLE
Outdated info in CONTRIBUTING.md

### ISSUE THREAD

**Issue by glumia** [cookiecutter/cookiecutter#1528]
Hi there! I took a detailed read to the `CONTRIBUTING.md` file and noticed that there is some outdated information:

- In [#create-cookiecutter-templates](https://github.com/cookiecutter/cookiecutter/blob/master/CONTRIBUTING.md#create-cookiecutter-templates) we suggest to create templates and then add them to the readme with a pull request. This is contradictory with what we state in [README.md#a-pantry-full-of-cookiecutters](https://github.com/cookiecutter/cookiecutter/blob/master/README.md#a-pantry-full-of-cookiecutters), where we implicitly tell template creators to just use the `cookiecutter-template` topic to make them discoverable (check c73ce79cc1ce47737ea1ceef2a96fee005f190ac).
- In [#coding-standards](https://github.com/cookiecutter/cookiecutter/blob/master/CONTRIBUTING.md#coding-standards) we say *"Write new code in Python 3"*. This is redundant now that the project doesn't support Python 2 anymore.
- The link to the pull requests checklist (https://gist.github.com/audreyr/4feef90445b9680475f2) in [#process-pull-requests](https://github.com/cookiecutter/cookiecutter/blob/master/CONTRIBUTING.md#process-pull-requests) and in [#responsibilities](https://github.com/cookiecutter/cookiecutter/blob/master/CONTRIBUTING.md#responsibilities) is broken.
- [#process-accepting-template-pull-requests](https://github.com/cookiecutter/cookiecutter/blob/master/CONTRIBUTING.md#process-accepting-template-pull-requests) this part can be removed given that we don't add cookiecutter templates to the `README.md` anymore.

Some other issues:
- In [#testing-with-tox](https://github.com/cookiecutter/cookiecutter/blob/master/CONTRIBUTING.md#testing-with-tox) the hyperlink 'pytest usage docs' is in inline code style for no good reason.
- In the first point of [#responsibilities](https://github.com/cookiecutter/cookiecutter/blob/master/CONTRIBUTING.md#responsibilities) it would be more correct to list `Windows, macOS and Linux` as supported platforms (Debian and Ubuntu are just two specific distros).

**Comment by glumia** [comment]
I recovered the pull requests checklist on the wayback machine: [link](https://web.archive.org/web/20171009135452/https://gist.github.com/audreyr/4feef90445b9680475f2). Should we add it as a separate file? (so that we are sure it doesn't get lost again)

By the way, @audreyfeldroy would that be ok for you?

**Comment by simobasso** [comment]
Hey @glumia, we just merged https://github.com/cookiecutter/cookiecutter/pull/1537!

Thanks for your contribution
