### ISSUE TITLE
The latest docs are for an unreleased version of cookiecutter

### ISSUE THREAD

**Issue by simobasso** [cookiecutter/cookiecutter#1530]
The docs are for an unreleased version of cookiecutter, although it has been merged to master, it has not been released on pypi.

_Originally posted by @samj1912 in https://github.com/cookiecutter/cookiecutter/issues/1115#issuecomment-747997573_

We should consider adding a banner that warns the user that the "latest" version is an unreleased version or deploy docs only for tags.

**Comment by samj1912** [comment]
If you have access to the readthedocs panel, you can hide the `latest` version from the dropdown and from search. That might be the easiest?

We can instead have a `stable` tag that points to the latest stable version.

**Comment by simobasso** [comment]
@samj1912 good points, thanks!

I will check tomorrow.

**Comment by insspb** [comment]
@simobasso @samj1912 
Fixed. By default https://cookiecutter.readthedocs.io/ should show last released version now. 
Latest tag available on selection.
