### ISSUE TITLE
Improve `--no-input` documentation

### ISSUE THREAD

**Issue by glumia** [cookiecutter/cookiecutter#1543]
Check https://github.com/cookiecutter/cookiecutter/issues/1201#issuecomment-830597644.

Currently it isn't clear from the documentation what exactly cookiecutter's behaviour is in case the `--no-input` flag is provided.

We should add the information about template's cache refresh and check if there's something else missing (by looking at what happens when `no_input` is `True` in the source code).

**Comment by jeremyswerdlow** [comment]
Hi there, was looking at starting to contribute and thought this would be a good issue with which to begin. However, I see that in HISTORY.md there is an accreditation to @pokoli for their documentation on this flag.

Is this issue still valid?

**Comment by glumia** [comment]
Hi @jeremyswerdlow, yes it is still valid! 

If you take a look at https://github.com/cookiecutter/cookiecutter/pull/701 you can see that it doesn't explain exactly what happens when you provide the `--no-input` flag on the command line (I remember noticing that template's cache refresh was only one of its undocumented side effects).

**Comment by jeremyswerdlow** [comment]
Great! If it's alright I'll take over this issue then!

**Comment by jeremyswerdlow** [comment]
Looks like the CR needs to be approved for testing by a maintainer, if someone has a chance

**Comment by insspb** [comment]
@jeremyswerdlow @glumia Thank you for contribution, will be in next release.
