### ISSUE TITLE
How to add comment in the template to be automatically removed by cookiecutter.

### ISSUE THREAD

**Issue by cccntu** [cookiecutter/cookiecutter#1585]
### Description:

Hi, I want to add a comment in the template, that is removed when running cookiecutter. How do I do that ?
Thanks!
```

# (template comment, describe the template): if abc, print 1, other wise print 2
{% if cookiecutter.abc %}
print(1)
{% else %}
print(2)
{% endif -%}
```

I guess this would work, but isn't very elegant:
```
{% if False %}
# template comment
{% endif -%}
```

**Comment by cjolowicz** [comment]
Cookiecutter uses Jinja as its template engine. Comments in Jinja work like this:

```jinja
{# a comment #}
```

You can find more information in Jinja's [Template Designer Documentation].

[Template Designer Documentation]: https://jinja.palletsprojects.com/en/3.0.x/templates/

**Comment by cccntu** [comment]
Thank you! @cjolowicz
