### ISSUE TITLE
New Release possible?

### ISSUE THREAD

**Issue by jensens** [cookiecutter/cookiecutter#1618]
Since there are some problems solved, would it be possible to get a fresh bug-fix release? Please.

**Comment by jensens** [comment]
I just dug a bit deeper in the commits here and saw there is is a pre-RC1 branch for a 2.0.0 release. Awesome 💯  

If there is need for help, like testing features or such just mention me!

**Comment by connerxyz** [comment]
Yes, would love to have this available. Thanks!

**Comment by jensens** [comment]
in progress
