### ISSUE TITLE
`cookiecutter --version` prints out the wrong Python version on 3.10

### ISSUE THREAD

**Issue by gotmax23** [cookiecutter/cookiecutter#1619]
``` console
$ cookiecutter --version
Cookiecutter 1.7.3 from /usr/lib/python3.10/site-packages (Python 3.1)
```

It should end with `(Python 3.10)` not `(Python 3.1)`. This seems to be the problematic code:

https://github.com/cookiecutter/cookiecutter/blob/f821895a0cb536a907ac2937471d7d4ac36fec75/cookiecutter/cli.py#L26-L31

**Comment by ozer619** [comment]
I would like to work on this issue.
