### ISSUE TITLE
Upgrade click in cookiecutter to avoid 'click>=7.0,<8.0.0'

### ISSUE THREAD

**Issue by gmelillo** [cookiecutter/cookiecutter#1640]
* Cookiecutter version: 2.0.2
* Template project url: N/A
* Python version: >= 3
* Operating System: All

### Description:

Using cookiecutter as a dependency for other projects that already use click is forcing to not upgrade to version 8.x because of the `setup.py` forcing the version to be lower than 8

**Comment by jaklan** [comment]
Yeah, that's a pity as Click 8.x is adopted pretty everywhere already...

**Comment by alkatar21** [comment]
I think this can be closed since it has been addressed?

**Comment by jaklan** [comment]
@alkatar21 but still not released...

**Comment by alkatar21** [comment]
I know, but mostly issues are closed when they are fixed, not when they are released, especially since it is not an issue in the current release.
