### ISSUE TITLE
Possibility to run a script while cookiecutting?

### ISSUE THREAD

**Issue by frankhuurman** [cookiecutter/cookiecutter#1652]
* Cookiecutter version: 1.7.3
* Template project url: -
* Python version: 3.8.10
* Operating System: Ubuntu 20.04 x64

### Description:
More of a question rather than an issue:
I've worked with both pre_gen and post_gen hooks which are great. But I really want some way to run a custom script to set some cookiecutter variables while generating the cookiecutter project.

For example I've made a script that pulls the person's name from the system's global git config file and would love to have that data injected into the cookiecutter.json so that I can use cookiecutter._git_user to set it somewhere in the rest of the project(a README in my case).
Now this script doesn't work of course because you can't access the cookiecutter.json with the pre_gen or post_gen hooks.

Is it possible to get this working some way?
All I can think of so far is to generate the README.md manually in the post_gen hook and add the username this way.

**Comment by dokempf** [comment]
This will be covered once https://github.com/cookiecutter/cookiecutter/pull/1240 is merged. You will be able to package your custom logic into a local Jinja extension and access it from all your templates.

**Comment by frankhuurman** [comment]
Thanks for the reply, I saw it has been merged but there wasn't a new release yet(or usage docs).
Hope it gets released soon!
