### ISSUE TITLE
Unable to load extension: No module named 'slugify'

### ISSUE THREAD

**Issue by dongmokevin** [cookiecutter/cookiecutter#1662]
* Cookiecutter version:
* Template project url:
* Python version: 3.9.6 and 3.10.4
* Operating System: windows10 pro

### Description:

Hello, Im trying to create a project a project using django cookiecutter and I ran into this issue several times.
I even tried to install slugify but still have the same issue.
### What I've run:

cookiecutter gh:cookiecutter/cookiecutter-django
You've downloaded C:\Users\kevin\.cookiecutters\cookiecutter-django before. Is it okay to delete and re-download it? [yes]: no
Do you want to re-use the existing version? [yes]: yes
Unable to load extension: No module named 'slugify'
![Capture d’écran (9)](https://user-images.githubusercontent.com/53708903/162802261-1e4ce111-64cf-48dc-896a-d8816ce9e75d.png)
![Capture d’écran (7)](https://user-images.githubusercontent.com/53708903/162802283-1187a139-2e23-401a-93e0-4966246cef36.png)

**Comment by luzfcb** [comment]
@dongmokevin What are the output messages of:


```python
python3 -m pip install cookiecutter --upgrade

cookiecutter gh:cookiecutter/cookiecutter-django
```

**Comment by dongmokevin** [comment]
Thank you very much it worked after the upgrade.

> @dongmokevin What are the output messages of:
> 
> ```python
> python3 -m pip install cookiecutter --upgrade
> 
> cookiecutter gh:cookiecutter/cookiecutter-django
> ```
