### ISSUE TITLE
Can I use .po/.pot files while generating project from template

### ISSUE THREAD

**Issue by PerchunPak** [cookiecutter/cookiecutter#1664]
I tried find something in web, but even [search on rtd](https://cookiecutter.readthedocs.io/en/stable/search.html?q=translate&check_keywords=yes&area=default) bugged when nothing found.

Or just can I choose language of generated language.

**Comment by insspb** [comment]
Cookiecutter do not support multi language for same project files. 
If you want to place templates in po/.pot - you can do it.
