### ISSUE TITLE
Is project dead?

### ISSUE THREAD

**Issue by lxhg** [cookiecutter/cookiecutter#1675]
- Can't install via pypi from master on debian testing (python 3.10.4)
- No releases in 1+ years
- Seems like abandoned project from open issues and pr

Is there fork at least in maintenance mode? Or is there any alternative?

Update after reading #1636 to the end. For some reason cookiecutter have releases in test pypi? I was able to install it from there and it seems to work. But it looks like this project does not have maintainer.

**Comment by mgaitan** [comment]
I would consider migrating your templates to [copier](https://copier.readthedocs.io/). It seems to be well maintained, solving several of the cookiecutter's current (and historical) limitations. 

See the comparison table
https://copier.readthedocs.io/en/stable/comparisons

**Comment by jensens** [comment]
Expect an official release soon. More information follows within next week.

**Comment by jensens** [comment]
Answer is: No.
