### ISSUE TITLE
Unable to parse YAML file `config` on Windows.

### ISSUE THREAD

**Issue by tobiasraabe** [cookiecutter/cookiecutter#1688]
* Cookiecutter version: 2.1
* Template project url: https://github.com/pytask-dev/cookiecutter-pytask-project/pull/22
* Python version: 3.7-3.10
* Operating System: Windows

### Description:

When I am running the tests for my cookiecutter on Windows, the cookiecutter cannot be created because: `InvalidConfiguration('Unable to parse YAML file C:\\Users\\...\\AppData\\Local\\Temp\\pytest-of-...\\pytest-713\\user_dir0\\config.'`

The content of the file is

```yaml
cookiecutters_dir: "C:\Users\user\AppData\Local\Temp\pytest-of-user\pytest-713\user_dir0\cookiecutters"
replay_dir: "C:\Users\user\AppData\Local\Temp\pytest-of-user\pytest-713\user_dir0\cookiecutter_replay"
```

I am not familiar enough with YAML, but single quotes seem to be required here for a valid YAML file. At least, that is what http://www.yamllint.com/ tells me.

The same tests work with cookiecutter v1.7.3. Surprisingly, the `config` file looks identical with double quotes around the paths. Did the YAML reader change?

### What I've run:

Run pytest in linked cookiecutter.

**Comment by tlambert03** [comment]
same here, https://github.com/tlambert03/pyrepo-cookiecutter/runs/6818457778?check_suite_focus=true

**Comment by kurtmckee** [comment]
@jensens @pydanny @ssbarnea Please close this issue.

It appears to be an issue in the test suite, caused by an older version of pytest-cookies, which has sinc been fixed.

**Comment by tobiasraabe** [comment]
Thanks for the notification. The issue has been fixed in https://github.com/hackebrot/pytest-cookies/pull/63.
