### ISSUE TITLE
Expressions are no longer properly parsed within filename

### ISSUE THREAD

**Issue by italomaia** [cookiecutter/cookiecutter#1696]
* Cookiecutter version:cookiecutter==2.1.1
* Template project url:https://github.com/italomaia/flask-empty
* Python version:3.10
* Operating System: Ubuntu 20

### Description:

I have a folder in my project  which should only exist if an config argument is true and I've been using an expression to render it or not. So, if the expression evaluates to empty, the folder is not created. This has worked for a long time, but after updating cookiecutter, it seems the way this is handle has changes. Instead of ignoring the file with empty name, it coerces to the partner folder and cookiecutter tries to create it again, which fails and breaks the build of my project. Was this an intended change in cookiecutter?

### What I've run:

Create the flask-empty project with the "use_security" option as "n".

**Comment by micahjsmith** [comment]
I don't know how you ever got that old approach to work :)

A better solution that will work right now is to clean up unneeded files in post-gen hooks https://cookiecutter.readthedocs.io/en/stable/advanced/hooks.html#example-conditional-files-directories

**Comment by italomaia** [comment]
=~
