### ISSUE TITLE
Use "squash and merge" for merging PRs

### ISSUE THREAD

**Issue by sisp** [cookiecutter/cookiecutter#1723]
Just a simple suggestion towards a cleaner Git history:

I think many projects these days have adopted the [squash-merging method](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests) for merging PRs. Typically, a PR consists of a single logical change of the target branch. This means, when a PR is merged, the Git history of the target branch receives one additional commit, even though the PR might have several commits due to code review and/or iterative development. Currently, it seems PRs are merged with an additional merge commit which clutters the Git history and makes it harder to read. If squash-merging was used, the Git history would become cleaner.

What do you think?

**Comment by jensens** [comment]
After the latest commits and digging through the history I had similar thoughts. 
I switched the settings from merge commits to squash commits. 
This may lead to smaller PRs, which is favorable.
