### ISSUE TITLE
Enable black force string formatting to exclude future discussion on strings

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1724]
Two year ago I rolled back changes of black for string normalization (#1298). The purpose of revert was to downgrade used python version and for easy PR merges (as PRs based on versions with different strings). 

At this time the time is come to implement such changes, because in several future refactoring we will anyway touch strings and if we implement black after refactoring it will be harder to find real last changes in git blame.

**Comment by liortct** [comment]
Hi @insspb 

We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened your issue at: https://github.com/cookieninja-generator/cookieninja/issues/44

We're trying to bring the life back to this amazing project.
We are committed to addressing each issue in up to 1 week from the day it's opened.
We'd really like you to join the fork, star it and contribute to it!

Thank you :)

**Comment by kurtmckee** [comment]
This will happen soon, after an additional backlog of PRs are closed or merged (down from 70 to only 25!) No issue is required to track this work, however, so I'm closing this.
