### ISSUE TITLE
Enable strict formatting checks for rst and markdown documentation files

### ISSUE THREAD

**Issue by insspb** [cookiecutter/cookiecutter#1730]
When in 2020 I wrote issue #1409 it was already clean that documentation need new life, and that there is some problem inside. But in this topic the documentation format was not discussed at all.

Later in 2022 @audreyfeldroy and @pydanny invited @ericof and @jensens to join a project. And they accept this invitation. And this is good when new people appear in core team. 

Unfortunately besides of release of 2.1.1 one of the first new 'requirements' became 1 sentence in documentation per line, with explanation that this is required for documentation translation. I was not able to find any public or private discussion on this topic and did not see any reason to implement this. That's why I am creating this issue.

I done a research in most popular python projects on python. With or without translated documentation and I was not able to find any one project, that match this rule. The closest that I was able to find is projects with 1 text block per line, but it was ansible, with much more wider community than ours. I also checked how documentation translated in django and did not find this rule in source files. All source files are formatted with 80-88 symbols rule, making these files easy readable in any mode.

I also though: Ok. If we want a rule, can we force it in linting? I checked popular doc8 checker and did not find such option there. At this point I became sure, that documentation should be readable in any IDE, text editor or as raw files in github without any additional manipulation.

That's why I done PR #1728 and #1729 

These to PRs close a question of format of documentation and rules of such formatting, making rules checked by strict linters.

Also these two PRs answers a question why we should not implement #1723, and why we should respect commit messages by developers. If we will implement #1723 information on little changes, separated in single commits will be lost. The information that will be available will contain all files that was changed in PR, was at related changes or not. Same will be true when PR contain related topic to PR title, but contain steps on how this was made, i.e. when changes are done step by step, and error can be placed on dedicated step, not in complete PR. this information is important in future. Browsing full PR can be very non-productive.

**Comment by jensens** [comment]
After checking back with @pydanny we stick to the sane rule as one sentence per line. I do not like to repeat myself, but docs are not code, other rules apply here. I wrote much more already as you know. I won't spent more energy on this discussion.
Cc @ericof
