### ISSUE TITLE
Feature-Request: Templates in context variables should support boolean values

### ISSUE THREAD

**Issue by italomaia** [cookiecutter/cookiecutter#1738]
* Cookiecutter version:2.1.1
* Python version:3.x

### Description:

As described here (https://cookiecutter.readthedocs.io/en/stable/advanced/templates_in_context.html), we expect template authors to be able to reuse values of previous keys from cookiecutter.json, but currently that is not possible if you are working with boolean values. I believe it would be very important to support this use case or describe an alternative way to do it in docs. Example:

// cookiecutter.json
```
{
"likes_potatoes": true,
"likes_mashed_potatoes": {{ cookiecutter.likes_potatoes }}
}
```
Above does not work. I would have to use double quotes, which would turn the value into a string, which would change how I evaluate it in the rest of the template.

**Comment by liortct** [comment]
Hey @italomaia.
I already added this feature and in cookiecutter 2.2.0 it will be released.
See in the close #1626 PR.
I advice to close this issue.

**Comment by avidspartan1** [comment]
I'd like to reopen this issue. I'm not able to use a template to make a cookiecutter variable use a Boolean data type.

Reusing @italomaia's example above, the following produces a String variable for `likes_mashed_potatoes`, when I'd expect for it to produce a Boolean:

```json
{
"likes_potatoes": false,
"likes_mashed_potatoes": "{{ cookiecutter.likes_potatoes }}"
}
```

Template example using above variables:

```bash
#!/bin/bash

{% if cookiecutter.likes_mashed_potatoes %}
echo "I like mashed potatoes!"
{% endif %}
```

The `echo "I like mashed potatoes"` line always renders, even when `likes_potatoes` is false.
