### ISSUE TITLE
Html

### ISSUE THREAD

**Issue by Ekimwaki1990** [cookiecutter/cookiecutter#1740]
How can one insert an image and a button in a search box
<!DOCTYPE html>
<html>
    <head>
        <title>tweeter.com</title>
        <link rel="stylesheet" href="tweet.css">
<style>

</style>
    </head>
    <body>
        <img class="profile-picture" src="thumbnails/fordmustang.jpeg">
<input class="searchbar"  type="text"  placeholder="what&#39;s happening&#63;" >
<button class="tweet-button">Tweet</button>

    </body>
</html>

**Comment by pydanny** [comment]
This issue is clearly for a project that isn't Cookiecutter.
