### ISSUE TITLE
Values in cookiecutter.json which have a boolean as default are still treated as strings

### ISSUE THREAD

**Issue by italomaia** [cookiecutter/cookiecutter#1742]
* Cookiecutter version:2.1.1

### Description:

Just tried using boolean values in my cookiecutter.json as suggested by the documentation. Even though, from the user's perspective, those are treated as boolean values (see here https://github.com/cookiecutter/cookiecutter/issues/1695), when used within templates, the values are actually strings. So, a cookiecutter.json configuration like this:

```
{
  "likes_potatoes": false
}
```

When used in a template like this:

```
{% if cookiecutter.likes_potatoes %}
Congrats, you win a potato!
{% else %}
No potatoes for you, then.
{% endif %}
```

Will always show "No potatoes for you, then."

To make the code above correct, the template needs to be written like this:

```
{% if cookiecutter.likes_potatoes == 'True' %}
Congrats, you win a potato!
{% else %}
No potatoes for you, then.
{% endif %}
```

Which is, in my opinion, counter intuitive. **I believe this is a bug.**

**Comment by alkatar21** [comment]
The feature is not released yet. The documentation can only be found under latest and is specified as from 2.2.0. In the current release (stable - 2.1.1) the feature is not yet included. See: https://cookiecutter.readthedocs.io/en/latest/advanced/boolean_variables.html

**Comment by italomaia** [comment]
Ah, ok then.
