### ISSUE TITLE
[Discussion] Dropping jinja2-time as dependency

### ISSUE THREAD

**Issue by tranzystorek-io** [cookiecutter/cookiecutter#1755]
* Cookiecutter version: 2.1.1
* Template project url: -
* Python version: 3.10
* Operating System: Void Linux

### Description:

I recently tried to package cookiecutter for Void Linux (https://github.com/void-linux/void-packages/pull/38176#issuecomment-1199183537), but was refused by the maintainers because of the jinja2-time dependency and its questionable state.

I'd like to ask if there's a solution on cookiecutter's side. I know it's a lot to ask to replace a dependency, but maybe this could benefit the project in general.

**Comment by jensens** [comment]
It is 65 LOC https://github.com/hackebrot/jinja2-time/blob/main/jinja2_time/jinja2_time.py (and some tests). 
One option is to copy it over here and update it if needed. 
I am -1 for removal.

**Comment by tranzystorek-io** [comment]
Would anyone be ooposed to a PR that inlines this functionality into cookiecutter?

**Comment by yuvaldolev** [comment]
Hi @tranzystorek-io 

We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened your issue at: https://github.com/cookieninja-generator/cookieninja/issues/31

We're trying to bring the life back to this amazing project.
We are committed to addressing each issue in up to 1 week from the day it's opened.
We'd really like you to join the fork, star it and contribute to it!

Thank you :)
