### ISSUE TITLE
Generate Context fails when a default list value provided

### ISSUE THREAD

**Issue by simonwardjones** [cookiecutter/cookiecutter#1757]
* Cookiecutter version: `2.1.1`

### Description:

Currently when including a list in a default context the generate context fails. For example if you had a default context as below with a list value for the "_copy_without_render" key.
```json
{
    "1": 2,
    "some_key": "some_val",
    "_copy_without_render": [
        "**/*.txt"
    ]
}
```
### What I've run:
I was using cookiecutter indirectly through cruft when I got the error. In particular in the cruft project there is currently an issue caused by this: https://github.com/cruft/cruft/issues/166.

**Comment by simonwardjones** [comment]
I created a PR to go along with this issue here: https://github.com/cookiecutter/cookiecutter/pull/1756 😄

**Comment by robmoorman** [comment]
Got the same issue

**Comment by adamcunnington-mlg** [comment]
is this now fixed?

**Comment by luisdavim** [comment]
This issue has been blocking me :(

**Comment by simonwardjones** [comment]
> is this now fixed? there hasn't been a pypi release since 1st June so if the fix is merged, I guess it is not yet released

I don't think this is fixed yet. I made a PR on cookie cutter here: https://github.com/cookiecutter/cookiecutter/pull/1756 but it is still awaiting review.

**Comment by samj1912** [comment]
This needs a fix from cookiecutter. Blocked on https://github.com/cookiecutter/cookiecutter/pull/1756
