### ISSUE TITLE
Feature request - print directory tree

### ISSUE THREAD

**Issue by liortct** [cookiecutter/cookiecutter#1765]
* Cookiecutter version: latest
* Template project url: https://github.com/liortct/SimplePythonApp.git
* Python version: 3.8
* Operating System: linux

### Description:
After generating a project via cookiecutter there is no indication for the user which files/directories were created.
I want the the directory tree to be printed to the console afterwards.

**Comment by supcik** [comment]
Hello I would like to work on this issue. Is it OK for you ?
