### ISSUE TITLE
insert/update a single line in a file

### ISSUE THREAD

**Issue by bytearchive** [cookiecutter/cookiecutter#1787]
* Cookiecutter version: latest
* Template project url: tutorial project
* Python version: 3.8
* Operating System: mac

### Description:

Is it possible to update an existing file with this tool? i.e. i have a non cookiecutter regular project in github, I clone it and I want to insert {{project.slug}} at line x in the a file i.e. I dont want to replace but insert this line

**Comment by kurtmckee** [comment]
@bytearchive I don't think it's possible to modify a single line in a file.

@jensens @pydanny @ssbarnea Please close this issue. It's a question and I think it's been answered.
