### ISSUE TITLE
Working with line-ends: Inverted attributes

### ISSUE THREAD

**Issue by Ikari33** [cookiecutter/cookiecutter#1792]
* Cookiecutter version: 2.1.1
* Template project url:
* Python version: 3.9.13
* Operating System: Windows 10

### Description:

In the documentation (link below) there is a code sample with "\n\r", but I think it is the opposite :)
For me it works with "\r\n". 
\r represents cr
\n represents lf

[docs/advanced/new_line_characters.rst](https://github.com/cookiecutter/cookiecutter/blob/2.1.1/docs/advanced/new_line_characters.rst)

**Comment by Lahiry** [comment]
I guess they did a mistake in the docs, indeed the correct order is "\r\n".

"The traditional order, when both control characters are used, is Carriage Return, then Line Feed.

The reason for this goes back to the old ASR-33 Teletype.

When a Carriage Return is issued to an ASR-33, the print head, if it is near the right margin, takes over a tenth of a second to return to the left margin, plus there is a bit of "bounce" when the left margin is hit.

If the order were Line Feed, then Carriage Return, the first printed character might occur a tenth of a second after the Carriage Return, and thus might end up printing (as a smear) halfway across the page. But if Line Feed comes after Carriage Return then the time taken by the Line Feed provides extra time for the print head to complete it's trip."

[StackOverflow](https://stackoverflow.com/questions/1885900/order-of-carriage-return-and-new-line-feed)

I'm going to make a PR to fix this. Please assign this issue to me! :)

**Comment by yuvaldolev** [comment]
Hi @Ikari33 & @Lahiry
We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have re-opened your issue at: https://github.com/cookieninja-generator/cookieninja/issues/28

We're trying to bring the life back to this amazing project.
We are committed to addressing each issue in up to 1 week from the day it's opened.
We'd really like you to join the fork, star it and contribute to it!

Thank you :)
