### ISSUE TITLE
Standard template fails due to Travis CI

### ISSUE THREAD

**Issue by carsten-engelke** [cookiecutter/cookiecutter#1807]
* Cookiecutter version: 2.1.1
* Template project url: https://cookiecutter-pypackage.readthedocs.io/
* Python version: 3.7
* Operating System: Windows

### Description:

The described "standard" template at: https://github.com/audreyfeldroy/cookiecutter-pypackage is using travis ci, which seems to have changed (and is not working without giving the company billing information). Shouldn't the standard template make use of open source software only? Which ones are the best alternative? -> being new to this tool, this already made me look into other boilerplate options for python.

**Comment by michaeljoseph** [comment]
Hi @carsten-engelke 👋🏼 I think this perhaps is an issue for the template project itself and not cookiecutter?

Several alternative templates are listed here: https://github.com/audreyfeldroy/cookiecutter-pypackage#similar-cookiecutter-templates

**Comment by carsten-engelke** [comment]
> Hi @carsten-engelke 👋🏼 I think this perhaps is an issue for the template project itself and not cookiecutter?
> 
> Several alternative templates are listed here: https://github.com/audreyfeldroy/cookiecutter-pypackage#similar-cookiecutter-templates

Travis not working for free is a problem with the template (that has been discussed for 2 years). There are several alternatives that solve it already. I posted the issue here, because I think it is a bad choice as standard template and might need a switch to one of the alternatives (e.g. https://github.com/zillionare/cookiecutter-pypackage)

**Comment by ZenulAbidin** [comment]
Hi guys, I'm working on a patch for pypackage that allows you to select between Github Actions and Travis CI. I think that should solve the problem.

**Comment by jensens** [comment]
This is OT here, please report over in the specific project.
