### ISSUE TITLE
A new Cookiecutter community fork named Cookieninja

### ISSUE THREAD

**Issue by yuvaldolev** [cookiecutter/cookiecutter#1810]
Unfortunately it seems that the Cookiecutter project is on hiatus, and new issues / PRs aren't being worked on.

We started working on a new community fork of the Cookiecutter project, named Cookieninja.
The fork is found at: https://github.com/cookieninja-generator/cookieninja

We have addresses many of the issues, and re-opened and merged the many of the PRs from the Cookiecutter project.

We're trying to bring the life back to the Cookiecutter project.
We are committed to addressing each issue in up to 1 week from the day it's opened, and reviewing and merging each PR in up to 2 weeks from the day it's opened (if there are no issues with it).
We'd really like you to join the fork, star it, contribute to it and create new issues!

Thank you :)

**Comment by insspb** [comment]
@yuvaldolev I wish you a good luck and hope you team will not be affected by internal decisions and project collectors, that by my opinion ruined original project. At least stopped me from contributing here. 

I pinned this issue, so other developers can see and use it. Last thing how I can help you.

My recommendation is to highlight original cookiecutter version you forked from in your readme.

**Comment by insspb** [comment]
@yuvaldolev Another one recommendation is to make an pull request to local project documentation, with your fork description and politics. Maybe somebody will merge it in future, and users may be interested in more active project.

**Comment by yuvaldolev** [comment]
@insspb

Thank you for your kind words, recommendations and for pinning this issue!
We would really love it if you'd like to contribute to the Cookieninja project, and star it ;)

Thanks again!

**Comment by exhuma** [comment]
Does the cookiecutter team have an official stance on this? I do have an open PR here and was contacted by the cookieninja devs for that reason. Naturally I would like the PR to be considered and either rejected or accepted. So a fresh new community gives me hope.

However, I don't feel comfortable about a new project for the following reasons:

* There has still been activity on cookiecutter only 4 months ago (according to the commit-logs). This is still below the 12 months laid out by the PyPA for abandoned projects.
* cookieninja has no fork-relation with cookiecutter. This makes both discoverability and potential downstream -> upstream merges a bit more difficult. I don't know whether they started with a new (disconnected) git history or not which would make this even harder.

An official statement by the cookiecutter devs would be nice to have to avoid splitting the community too much. If the official stance is that "cookuecutter" is no longer maintained, then new contributors can find their way to cookieninja. If no such statement is given, cookiecutter may still receive contrinutions.

If both projects remain maintained that's of course fine too :)

**Comment by pydanny** [comment]
Cookiecutter has had semi-active maintainers for some time now. As we all have jobs and families and this is a mostly unsponsored project, there's only so much bandwidth.

If anyone in this thread wants to join this as a maintainer, we're open to discussion. Here's our baseline of rules:

- Semantic versioning all the way
- Any new features have to work on Windows, Mac, and Linux. No exceptions
- This project was created by one of the founders of pyladies, has a code of conduct, embraces diversity, and expects all maintainers to follow the same views

Closing this ticket as we'll have maintainers active again soon.

**Comment by exhuma** [comment]
Thank you @pydanny for the update and also for your impactful work you've done with cookiecutter. I'm glad to see that the project is still alive and will stick around here. I might lend a hand with project maintenance but I too have a fairly busy schedule and can only do so much. I have been developing Python almost full-time since 2004 so I know my way around. If you want to exchange a few messages to see if I could be a good fit for the project you can gladly reach me via mail or twitter.
