### ISSUE TITLE
Use cookiecutter.io site as the project homepage in the github description

### ISSUE THREAD

**Issue by kishaningithub** [cookiecutter/cookiecutter#1816]
In the project documentation i see no references to the [cookiecutter.io](https://www.cookiecutter.io/) site (screenshots below). If it is a site this project is maintaining then it makes sense to put that as the project home page in the github project description and other documentations. What do you think?

### Project description
<img width="311" alt="Screenshot 2023-02-08 at 6 20 34 PM" src="https://user-images.githubusercontent.com/763760/217534451-54c3dd34-29c9-4de6-97d0-ea2859d4835a.png">

### Read the docs site
<img width="800" alt="Screenshot 2023-02-08 at 6 23 02 PM" src="https://user-images.githubusercontent.com/763760/217534965-c91bc742-3c43-45a1-b4df-5afdfc900dcf.png">

### Project readme
<img width="800" alt="Screenshot 2023-02-08 at 6 24 16 PM" src="https://user-images.githubusercontent.com/763760/217535255-18ddd377-4746-464d-9bb3-e55feba4a9ae.png">

**Comment by obvionaoe** [comment]
I think the website is maintained by someone other than the project maintainers

**Comment by kurtmckee** [comment]
Agreed, it appears that website is not owned by cookiecutter maintainers.

@pydanny @jensens @ssbarnea Please close this issue.
