### ISSUE TITLE
Convert any git repo into a cookiecutter projects template.

### ISSUE THREAD

**Issue by MacHu-GWU** [cookiecutter/cookiecutter#1818]
* Cookiecutter version: ANY
* Template project URL: ANY
* Python version: Python3.7+
* Operating System: Win / Mac / Linux

### Description:

``cookiecutter`` is awesome! In the real-world, people usually start with a concrete, working project. Once they are happy with this best practice, then they will convert it into a template for future use. 

To solve this problem, I created a project [cookiecutter_maker](https://github.com/MacHu-GWU/cookiecutter_maker-project), it is a Python open-source tool that can convert any git repo into a cookiecutter projects template.

Example:

```python
from cookiecutter_maker.maker import Maker

maker = Maker.new(
    input_dir="/path-to-input-dir/my_awesome_project",
    output_dir="/path-to-output-dir",
    mapper=[
        ("my_awesome_project", "package_name"),
    ],
    include=[],
    exclude=[
        # dir
        ".venv",
        ".pytest_cache",
        ".git",
        ".idea",
        "build",
        "dist",
        "htmlcov",
        # file
        ".coverage",
    ],
    overwrite=True,
    debug=True,
)
maker.templaterize()
```

**Does cookiecutter plan to add similar feature?**

**Comment by kurtmckee** [comment]
@MacHu-GWU That's an awesome idea! One thing to consider based on the example above: perhaps the exclusions could be read from the `.gitignore` file!

I'm not a maintainer, but my guess is that cookiecutter is unlikely to add a similar "project->template" feature.

@jensens @pydanny @ssbarnea Please close this issue. It's a question and I think it has been answered.
