### ISSUE TITLE
can i use cookiecutter on a template folder and have another cookiecutter in it

### ISSUE THREAD

**Issue by TamarLevy** [cookiecutter/cookiecutter#1822]
I have this file structure:

```
/folder1
   /{{cookiecutter.project_slug}}
       /src
          /{{cookiecutter.project_slug}}{{cookiecutter.package_type}}
               test.py
               main.py
       README.md
       cookiecutter.json
   cookiecutter.json
```

folder1/cookiecutter.json contains:
```
{ 
   project_slug = "project name"
}
```

{{cookiecutter.project_slug}}/cookiecutter.json contains:
```
{
  package_type = "regular"
}
```

I want to operate cookiecutter twice first on: project_slug and second time inside {{cookiecutter.project_slug}}
I cannot run cookiecutter on this file structure, is there anyway I can allow it? maybe using hooks. I just dont know how.

I tried to use this file structure but it looks like cooikecutter expect to have only one template on folder ({{cookiecutter.project_slug}}) and not two, concatenation of two templates ({{cookiecutter.project_slug}}{{cookiecutter.package_type}})
```

**Comment by kurtmckee** [comment]
@TamarLevy Instead of using multiple `cookiecutter.json` files, perhaps you could use a single file:

```json
{
  "project_slug": "project name",
  "package_type": "regular"
}
```

As an alternative, if the package type is hardcoded, perhaps the directory could contain the word "regular". Using the example above:

```diff
- /{{cookiecutter.project_slug}}{{cookiecutter.package_type}}
+ /{{cookiecutter.project_slug}}regular
```

@jensens @pydanny @ssbarnea Please close this issue.
