### ISSUE TITLE
Add parameter description field to `cookiecutter.json`

### ISSUE THREAD

**Issue by thomas-bc** [cookiecutter/cookiecutter#1835]
**This is an enhancement proposition**

### Rationale
We use cookiecutter to allow users (**who may be unaware of what cookiecutter is**) to quickly generate files through a custom command-line utility. One caveat is that when the user is asked for input, it gets prompts like the following
```
project_name [MyProject]:
project_branch_or_tag [devel]:
Select install_venv:
1 - yes
2 - no
Choose from 1, 2 [1]:
```
While variables can have a rather verbose name, it is not always the case that the name only can be entirely self-explanatory.
**It would be nice if `cookiecutter.json` would allow some more verbose (e.g. raw text) input along with the variables, to be displayed at prompt-time.**

### Proposition description

Since the parameters are configured with a `cookiecutter.json`, it seems like it should be doable to add some kind of description field to parameters so that the displayed when cookiecutter launches its prompts. For example, following the above example, we could imagine something like the following (or any other structure):

```
{
  "project_name": "MyProject",
  "project_branch_or_tag": "devel",
  "install_venv": ["yes", "no"],
  "__internal_use": {
       "parameter_descriptions": {
           "project_name": "Select your project name:",
           "project_branch_or_tag": "Which branch do you want to checkout?",
           "install_venv": "Do you wish to install a Python virtual environment?" 
  }
}
```

Which would prompt with the following:

```
Select your project name [MyProject]:
Which branch do you want to checkout? [devel]:
Do you wish to install a Python virtual environment?:
1 - yes
2 - no
Choose from 1, 2 [1]:
```
<br><br>
I am unaware of the cookiecutter implementation details, so there may be things I have overlooked. This is a mere feedback from a grateful user :)

**Comment by thomas-bc** [comment]
From looking at https://github.com/cookiecutter/cookiecutter/blob/main/cookiecutter/prompt.py, I don't see any blockers that would prevent this from being doable

**Comment by andrewthetechie** [comment]
@thomas-bc I wrote a project to allow you to write your cookeicutter.json file in toml, something I call a cookiecutter.desc, that allows you to add basic typing and descriptions to a template inputs. My utility then converts the cookiecutter.desc into a cookiecutter.json.

Let me know if you think it might be useful to you

**Comment by vemonet** [comment]
I would be really interested by this feature, the current IDs with underscore are not really user friendly

It could also be simplified it to:

```json
{
  "project_name": "MyProject",
  "project_branch_or_tag": "devel",
  "install_venv": ["yes", "no"],
  "__descriptions" {
           "project_name": "Select your project name:",
           "project_branch_or_tag": "Which branch do you want to checkout?",
           "install_venv": "Do you wish to install a Python virtual environment?" 
  }
}
```

And just use a key starting with `__` for any other meta properties

**Comment by vemonet** [comment]
I implemented it in this branch: https://github.com/vemonet/cookiecutter/tree/add-questions-descriptions it was quite straightforward, cf. the commit https://github.com/vemonet/cookiecutter/commit/070049e0030472432c6a502b396056af86add79b


I took the approach to have a `__internal_use` dir, it can be changed easily if we want

Example of a config file:

```json
{
    "package_name": "my-package",
    "module_name": "{{ cookiecutter.package_name.replace('-', '_') }}",
    "short_description": "A nice python package",
    "__internal_use": {
        "descriptions": {
            "package_name": "Select your package name:",
            "module_name": "Select your module name:"
        }
    }
}
```

The 2 first questions will use the description provided, the 3rd one will use the variable name since there is no description provided

I will add tests and send a PR if this is a feature that you are interested to integrate

**Comment by thomas-bc** [comment]
That's awesome! Thank you very much 🎉
