### ISSUE TITLE
Could not create repo

### ISSUE THREAD

**Issue by Vic3sax** [cookiecutter/cookiecutter#1863]
* Cookiecutter version:latest version
* Template project url:https://github.com/Vic3sax/Diabetes-Prediction-Model
* Python version:3.10
* Operating System:macOS

### Description:

// REPLACE ME: What are you trying to get done, what has happened, what went wrong, and what did you expect?

### What I've run: cookiecutter https://github.com/Vic3sax/Diabetes-Prediction-Model

```
 A valid repository for "https://github.com/Vic3sax/Diabetes-Prediction-Model" could not be found in the following locations:
/Users/appleplay/.cookiecutters/Diabetes-Prediction-Mode
```

**Comment by kurtmckee** [comment]
Based on [the usage documentation](https://cookiecutter.readthedocs.io/en/stable/usage.html) it appears that the command should be:

```shell
cookiecutter https://github.com/Vic3sax/Diabetes-Prediction-Model.git
```

You might also use the "gh" shorthand prefix:

```shell
cookiecutter gh:Vic3sax/Diabetes-Prediction-Model
```

**Comment by Vic3sax** [comment]
I used both and it didn't work, I might just uninstall cookiecutter and reinstall it

**Comment by kurtmckee** [comment]
Hmm...I'm looking at that repo now and it doesn't look like it's a valid cookiecutter repo. I would expect it to have a directory named something like `{{ cookiecutter.project_name }}` and a file named `cookiecutter.json`. That may be the source of the problem.
