### ISSUE TITLE
`cookiecutter.extensions.TimeExtension` is a breaking change in 2.2.0

### ISSUE THREAD

**Issue by tranzystorek-io** [cookiecutter/cookiecutter#1888]
* Cookiecutter version: 2.2.0
* Template project url: -
* Python version: -
* Operating System: -

### Description:

As mentioned in https://github.com/cookiecutter/cookiecutter/pull/1779#issuecomment-1624206505, the change I introduced is not backward-compatible with cookiecutters created using versions `<2.2.0`

My initial thought is to add a `jinja2_time` module or name alias that points to the current `cookiecutter.extensions.TimeExtension` to make older cookiecutters work correctly, at least for a while. Note, I am not as familiar with python to know how to best implement this, comments welcome.

Ping @henryiii as original reporter

EDIT: unless I'm wrong this should be perfectly backward compatible after all, at least for the template creators, since the time extension is available as a built-in.

**Comment by tranzystorek-io** [comment]
Hm, on second thought, @henryiii you mentioned the example in documentation, but haven't templates like `{% now %}` worked out of the box since we include jinja2_time by default? The `"_extensions": ["jinja2_time.TimeExtension"]` shouldn't even be needed IIUC.

**Comment by henryiii** [comment]
I've added what I was thinking to the docs as a PR. If you wanted to have a backward-compat shim, I'd recommend:

```diff
diff --git a/cookiecutter/environment.py b/cookiecutter/environment.py
index 50e4dd2..e13e486 100644
--- a/cookiecutter/environment.py
+++ b/cookiecutter/environment.py
@@ -3,6 +3,9 @@ from jinja2 import Environment, StrictUndefined

 from cookiecutter.exceptions import UnknownExtension

+import warnings
+import importlib.util
+

 class ExtensionLoaderMixin:
     """Mixin providing sane loading of extensions specified in a given context.
@@ -46,8 +49,17 @@ class ExtensionLoaderMixin:
             extensions = context['cookiecutter']['_extensions']
         except KeyError:
             return []
-        else:
-            return [str(ext) for ext in extensions]
+
+        str_extensions = [str(ext) for ext in extensions]
+
+        # Cookiecutter <2.2 installed jinja2_time extension by default and
+        # featured it in the docs, so protect that as a special case here:
+        J2T = "jinja2_time.TimeExtension"
+        if J2T in extensions and importlib.util.find_spec("jinja2_time") is None:
+            warnings.warn("jinja2_time extensions not installed, but functionality already present. Consider removing it from _extensions", stacklevel=1)
+            str_extensions.remove(J2T)
+
+        return str_extensions


 class StrictEnvironment(ExtensionLoaderMixin, Environment):
```

**Comment by jamesmyatt** [comment]
When was `cookiecutter.extensions.TimeExtension` added?

**Comment by henryiii** [comment]
You don't need to do `"_extensions": ["cookiecutter.extensions.TimeExtension"]`, it's already pre-loaded and works just like the classic TimeExtension. Before 2.2, `"_extensions": ["jinja2_time.TimeExtension"]` wasn't needed either to use the time extensions (it was pre-loaded), but it was in the documentation as an example, so I'd assume many projects (at least [177 on github](https://github.com/search?type=code&q=path%3Acookiecutter.json+jinja2_time+NOT+is%3Afork) not counting forks) looking to add time add this `_extensions` entry, even if it was not needed.

**Comment by jamesmyatt** [comment]
Yeah. Looks like just removing `jinja2_time.TimeExtension` from the extensions works anyway.
