### ISSUE TITLE
Support lists that are not options

### ISSUE THREAD

**Issue by balint-backmaker** [cookiecutter/cookiecutter#1892]
* Cookiecutter version: 2.2.0
* Template project url: N/A
* Python version: 3.10 (but I suspect this will be an issue with other versions too)
* Operating System: N/A

### Description:

Cookiecutter had an old issue where lists are only ever considered as options.

A workaround at the time was suggested via https://github.com/cookiecutter/cookiecutter/issues/479 this was working fine for us until `2.1.0`
But then this workaround was broken in https://github.com/cookiecutter/cookiecutter/pull/1692 which got released under `2.2.0`

### What I've run

Example `cookiecutter.json`:
```json
{
    "deployments": {
        "preprod": ["eu","us","ap"],
        "prod": ["eu", "us", "ap"]
    }
}
```

Example `context.json`:
```json
{
    "deployments": {
        "preprod": ["eu"],
        "prod": ["eu"]
    }
}
```

After running with `--no-input`, I've got this error:
```
ValueError: ['eu'] provided for choice variable prod, but the choices are ['eu', 'us', 'ap'].
```

### Porposed solution
I had a few ideas how this can be handled. 
For brevity, I've boiled down to a top-choice that can keep changes to a minimum.
This can be encapsulated within [apply_overwrites_to_context](https://github.com/cookiecutter/cookiecutter/blob/main/cookiecutter/generate.py#L49-L77)

The idea is to support "multi-choices" implicitly and only for lists:
- when running `apply_overwrites_to_context`
- if `context_value` is a list
- and `overwrite` is also a list
- then `intersect` for validation and pass if all values are permitted
- otherwise just run the original check to permit the value chosen

In my view prompting would be unchanged as the primary use-case here is with `--no-input`.

**Comment by sspans-sbp** [comment]
This is also affecting our use of cookiecutter. Would be nice to see a solution in a reasonable time-frame.

**Comment by mforbes** [comment]
This is also hurting us.  Lists nested in a dictionary can be specified, but they cannot be overwritten, making them rather useless.

**Comment by ryanpeach** [comment]
Where did you document this feature?
