### ISSUE TITLE
Missing template creators documentation

### ISSUE THREAD

**Issue by cmlccie** [cookiecutter/cookiecutter#1970]
* Cookiecutter version: 2.4.0

### Description:

Trying to find and access documentation for template creators; the [Learn More](https://cookiecutter.readthedocs.io/en/latest/template-author.html) link for Template Creators in the [README.md](https://github.com/cookiecutter/cookiecutter/blob/2.4.0/README.md#for-template-creators) is broken - users get a 404 page not found response from the documentation site.

### What I've run:

- Checked the [docs/](https://github.com/cookiecutter/cookiecutter/tree/2.4.0/docs) directory. 

**It looks like the`template-author.rst` is missing.** Perhaps this was an omission or maybe it is future work?

**Comment by kurtmckee** [comment]
This issue has been resolved. Thanks for reporting this!
