### ISSUE TITLE
Cannot properly override boolean variable from command line

### ISSUE THREAD

**Issue by wenjuno** [cookiecutter/cookiecutter#1973]
* Cookiecutter version: 2.4.0
* Template project url: N/A
* Python version: 3.10
* Operating System: Linux

### Description:

I tried to use the boolean variable. It works great when generating from interactive prompt. But when I try to use --no-input with command line context it doesn't propagate words like "no" or "false" as false value, but rather it seems to take it as string value, so if I pass an empty string it will be evaluated to false.

Here is my cookiecutter.json:
```json
{
  "project_name": "test_boolean",
  "generate_text": true
}
```

I have a file with template:
```
{% if cookiecutter.generate_text %}
Hello, world!
{% endif %}
```

If I run `cookiecutter --no-input -f . generate_text=false`, the generated file still has the "Hello, world!". But if i use `generate_text=""` the generated file will be empty.

**Comment by tylermilner** [comment]
I ran into this issue as well. Is the `documentation` tag for this issue correct? It seems like a possible bug since it causes different behavior when running interactively vs silently. I outlined some [repro steps here](https://github.com/tylermilner/cookiecutter-boolean-variable-override-bug) in case the original post was not clear.

I took a stab at fixing this so I'll open a PR shortly.

**Comment by wkrill** [comment]
As a workaround you can convert the string to boolean in a pre-gen hook:
```python
# hooks/pre_gen_project.py
'''
{% if cookiecutter.generate_text == "true" or cookiecutter.generate_text == true %}
{{cookiecutter.update({"generate_text": true })}}
{% else %}
{{cookiecutter.update({"generate_text": false })}}
{% endif %}
'''
```

**Comment by scprek** [comment]
I found that I needed to capitalize the the boolean in the command line. `True|False`

And then in the hooks I needed to remove teh `''` wrapper around the templates and tell the python linter to ignore

```python
# We cannot wrap the cookiecutter templates in '' because it will change the type from boolean to string
# See: https://flake8.pycqa.org/en/latest/user/error-codes.html
has_api = {{ cookiecutter.has_api }} # noqa: F821
```

I print these in the post_gen hook
```python
has_api: True (type: <class 'bool'>)
```
