### ISSUE TITLE
Reporting LGPL license in some dependency

### ISSUE THREAD

**Issue by DhavalRepo18** [cookiecutter/cookiecutter#1978]
* Cookiecutter version: main

### Description:

We found chardet has LGPL license. 
This package chardet is a dependency of binaryornot which is a dependency of cookie-cutter.

Is there any way to make binaryornot as optional package?

**Comment by DhavalRepo18** [comment]
Please see here - https://docs.python-requests.org/en/latest/user/advanced/
The "Encodings" Session.

**Comment by kurtmckee** [comment]
There is no issue using chardet as a library; binaryornot simply calls `chardet.detect()` and would not be considered a derivative work. Neither is cookiecutter considered a derivative work of binaryornot.

The LGPL license only applies to chardet.
