### ISSUE TITLE
Cookiecutter Setup Issue

### ISSUE THREAD

**Issue by TrillAstro** [cookiecutter/cookiecutter#1998]
TrillAstro ➜ /workspaces/cookiecutter (main) $ pip install pipx
Collecting pipx
  Downloading pipx-1.3.3-py3-none-any.whl.metadata (17 kB)
Collecting argcomplete>=1.9.4 (from pipx)
  Downloading argcomplete-3.2.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: packaging>=20 in /home/codespace/.local/lib/python3.10/site-packages (from pipx) (23.2)
Requirement already satisfied: platformdirs>=2.1 in /home/codespace/.local/lib/python3.10/site-packages (from pipx) (4.1.0)
Requirement already satisfied: tomli in /home/codespace/.local/lib/python3.10/site-packages (from pipx) (2.0.1)
Collecting userpath!=1.9.0,>=1.6 (from pipx)
  Downloading userpath-1.9.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: click in /home/codespace/.local/lib/python3.10/site-packages/click-8.1.7-py3.10.egg (from userpath!=1.9.0,>=1.6->pipx) (8.1.7)
Downloading pipx-1.3.3-py3-none-any.whl (63 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 kB 1.9 MB/s eta 0:00:00
Downloading argcomplete-3.2.1-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 1.3 MB/s eta 0:00:00
Downloading userpath-1.9.1-py3-none-any.whl (9.1 kB)
Installing collected packages: userpath, argcomplete, pipx
Successfully installed argcomplete-3.2.1 pipx-1.3.3 userpath-1.9.1
@TrillAstro ➜ /workspaces/cookiecutter (main) $ https://app.insomnia.rest/app/auth-app/?loginKey=gMwGIbp534SbsKVrQ9v91kQbwqWzPJThDySeYzP%252Bzno%253D
bash: https://app.insomnia.rest/app/auth-app/?loginKey=gMwGIbp534SbsKVrQ9v91kQbwqWzPJThDySeYzP%252Bzno%253D: No such file or directory
@TrillAstro ➜ /workspaces/cookiecutter (main) $ pip install cookiecutter
Requirement already satisfied: cookiecutter in /home/codespace/.local/lib/python3.10/site-packages/cookiecutter-2.5.0-py3.10.egg (2.5.0)
Requirement already satisfied: binaryornot>=0.4.4 in /home/codespace/.local/lib/python3.10/site-packages/binaryornot-0.4.4-py3.10.egg (from cookiecutter) (0.4.4)
Requirement already satisfied: Jinja2<4.0.0,>=2.7 in /home/codespace/.local/lib/python3.10/site-packages (from cookiecutter) (3.1.2)
Requirement already satisfied: click<9.0.0,>=7.0 in /home/codespace/.local/lib/python3.10/site-packages/click-8.1.7-py3.10.egg (from cookiecutter) (8.1.7)
Requirement already satisfied: pyyaml>=5.3.1 in /home/codespace/.local/lib/python3.10/site-packages (from cookiecutter) (6.0.1)
Requirement already satisfied: python-slugify>=4.0.0 in /home/codespace/.local/lib/python3.10/site-packages/python_slugify-8.0.1-py3.10.egg (from cookiecutter) (8.0.1)
Requirement already satisfied: requests>=2.23.0 in /home/codespace/.local/lib/python3.10/site-packages (from cookiecutter) (2.31.0)
Requirement already satisfied: arrow in /home/codespace/.local/lib/python3.10/site-packages (from cookiecutter) (1.3.0)
Requirement already satisfied: rich in /home/codespace/.local/lib/python3.10/site-packages/rich-13.7.0-py3.10.egg (from cookiecutter) (13.7.0)
Requirement already satisfied: chardet>=3.0.2 in /home/codespace/.local/lib/python3.10/site-packages/chardet-5.2.0-py3.10.egg (from binaryornot>=0.4.4->cookiecutter) (5.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/codespace/.local/lib/python3.10/site-packages (from Jinja2<4.0.0,>=2.7->cookiecutter) (2.1.3)
Requirement already satisfied: text-unidecode>=1.3 in /home/codespace/.local/lib/python3.10/site-packages/text_unidecode-1.3-py3.10.egg (from python-slugify>=4.0.0->cookiecutter) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.23.0->cookiecutter) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.23.0->cookiecutter) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/python/3.10.13/lib/python3.10/site-packages (from requests>=2.23.0->cookiecutter) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /home/codespace/.local/lib/python3.10/site-packages (from requests>=2.23.0->cookiecutter) (2023.11.17)
Requirement already satisfied: python-dateutil>=2.7.0 in /home/codespace/.local/lib/python3.10/site-packages (from arrow->cookiecutter) (2.8.2)
Requirement already satisfied: types-python-dateutil>=2.8.10 in /home/codespace/.local/lib/python3.10/site-packages (from arrow->cookiecutter) (2.8.19.14)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/codespace/.local/lib/python3.10/site-packages/markdown_it_py-3.0.0-py3.10.egg (from rich->cookiecutter) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/codespace/.local/lib/python3.10/site-packages (from rich->cookiecutter) (2.17.2)
Requirement already satisfied: mdurl~=0.1 in /home/codespace/.local/lib/python3.10/site-packages/mdurl-0.1.2-py3.10.egg (from markdown-it-py>=2.2.0->rich->cookiecutter) (0.1.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.10/site-packages (from python-dateutil>=2.7.0->arrow->cookiecutter) (1.16.0)
@TrillAstro ➜ /workspaces/cookiecutter (main) $ pipx run cookiecutter gh:audreyfeldroy/cookiecutter-pypackage
Traceback (most recent call last):
  File "/home/codespace/.python/current/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/pipx/main.py", line 885, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/pipx/main.py", line 197, in run_pipx_command
    commands.run(
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/pipx/commands/run.py", line 195, in run
    content = None if spec is not None else maybe_script_content(app, is_path)
  File "/usr/local/python/3.10.13/lib/python3.10/site-packages/pipx/commands/run.py", line 52, in maybe_script_content
    return app_path.read_text(encoding="utf-8")
  File "/usr/local/python/3.10.13/lib/python3.10/pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/python/3.10.13/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
IsADirectoryError: [Errno 21] Is a directory: 'cookiecutter'
@TrillAstro ➜ /workspaces/cookiecutter (main) $ ls
AUTHORS.md          HISTORY.md   Makefile     build         cookiecutter.egg-info  logo            setup.py               tox.ini
CODE_OF_CONDUCT.md  LICENSE      README.md    codecov.yml   dist                   pyproject.toml  test_requirements.txt
CONTRIBUTING.md     MANIFEST.in  __main__.py  cookiecutter  docs                   setup.cfg       tests
@TrillAstro ➜ /workspaces/cookiecutter (main) $ ls
AUTHORS.md          HISTORY.md   Makefile     build         cookiecutter.egg-info  logo            setup.py               tox.ini
CODE_OF_CONDUCT.md  LICENSE      README.md    codecov.yml   dist                   pyproject.toml  test_requirements.txt
CONTRIBUTING.md     MANIFEST.in  __main__.py  cookiecutter  docs                   setup.cfg       tests
@TrillAstro ➜ /workspaces/cookiecutter (main) $ cd cookiecutter
@TrillAstro ➜ /workspaces/cookiecutter/cookiecutter (main) $ ls
VERSION.txt  __main__.py  config.py       exceptions.py  find.py      hooks.py  main.py    replay.py      utils.py  zipfile.py
__init__.py  cli.py       environment.py  extensions.py  generate.py  log.py    prompt.py  repository.py  vcs.py
@TrillAstro ➜ /workspaces/cookiecutter/cookiecutter (main) $ pipx run cookiecutter gh:audreyfeldroy/cookiecutter-pypackage
⚠️  cookiecutter is already on your PATH and installed at /home/codespace/.local/bin/cookiecutter. Downloading and running anyway.
  [1/15] full_name (Audrey Roy Greenfeld):

**Comment by alanverresen** [comment]
I could not recreate the problem, but **if there's an issue, it definitely seems to lie with pipx, not cookiecutter**. The `IsADirectoryError` is raised by pipx, and points out that there's a directory named `cookiecutter` in your current directory, and that this is a problem. The existence of that directory is confirmed later on when you run the `ls` command, and the error is fixed once you change to the directory named `cookiecutter`, which does not contain a directory with that name.

**Try to put more effort in your issue descriptions**; just dumping your shell's history isn't a good way to submit an issue, especially when there's a template. This puts all the effort on the shoulders of others, and I'm not sure if I've missed something. I hope that if you open an issue with the `pipx` project, that you'll actually try to put some effort into your submission. **Perhaps most importantly, it seems like your dump includes a random URL with a key that may or may not be sensitive. Make sure to take the steps to prevent any harm if necessary.**

**Comment by jensens** [comment]
I agree: this s unrelated.
