### ISSUE TITLE
pyfakefs for testing filesystem setup

### ISSUE THREAD

**Issue by michaeljoseph** [cookiecutter/cookiecutter#223]
https://code.google.com/p/pyfakefs/
https://code.google.com/r/jmcgeheeiv-pyfakefs/

**Comment by jmcgeheeiv** [comment]
pyfakefs is indeed cool.  I have used it a lot and it works great.

I ported [pyfakefs to GitHub](https://github.com/jmcgeheeiv/pyfakefs), added documentation and I have accepted a few pull requests.  I am working on adding CI now.

pyfakefs lives.  Are you still interested?  Which Python versions do you need?
