### ISSUE TITLE
full_name does not take umlauts

### ISSUE THREAD

**Issue by a7p** [cookiecutter/cookiecutter#26]
If entering a full_name containing an umlaut in python 2.7 throws an  UnicodeDecodeError.

**Comment by sdsaati** [comment]
I  fixed this by ignoring some files I don't want to be parsed by cookiecutter/jinja2: I added this at the beginning of my cookiecutter.json file:
```json
"_copy_without_render": [
    "*.o",
    "*.exe",
    "*.so",
    "*.a",
    "*.lib",
    "*.obj",
    "*.dll",
    "*.png",
    "*.jpg"
  ],
```
