### ISSUE TITLE
Test all combinations of cookiecutter() params and command line args

### ISSUE THREAD

**Issue by audreyfeldroy** [cookiecutter/cookiecutter#273]
I noticed that a lot of test cases are missing in `test_main.py`:
- [ ] All combinations of parameters passed into the `cookiecutter()` function
- [ ] All combinations of arguments passed into the `cookiecutter` command-line command

Before we get any fancier with additional parameters/arguments, we need to make sure that all edge cases are covered.

**Comment by kurtmckee** [comment]
I'm closing this ticket due to its age.
