### ISSUE TITLE
bitbucket private repo pull against git does not work

### ISSUE THREAD

**Issue by vfulco** [cookiecutter/cookiecutter#353]
I am under the impression that bitbucket connectivity is not yet available?  Have tried a couple of different ways to pull from a private bucket with the --no-input CLI command and getting a permission denied.  I've verified service has my pub key.  Since i am fairly new at python debugging, wanted to ask to make sure.  I should mention I am building a Dockerfile and trying to pull in a modded repo.  The consistent error message is: 

Cloning into 'cookiecutter-flask'...
Warning: Permanently added the RSA host key for IP address '131.103.20.167' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Traceback (most recent call last):
  File "/usr/local/bin/cookiecutter", line 9, in <module>
    load_entry_point('cookiecutter==0.8.0', 'console_scripts', 'cookiecutter')()
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/main.py", line 171, in main
    cookiecutter(args.input_dir, args.checkout, args.no_input)
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/main.py", line 82, in cookiecutter
    no_input=no_input
  File "/usr/local/lib/python2.7/dist-packages/cookiecutter/vcs.py", line 92, in clone
    subprocess.check_call([repo_type, 'clone', repo_url], cwd=clone_to_dir)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'git', u'clone', 'git@bitbucket.org:vfulco1/cookiecutter-flask.git']' returned non-zero exit status 128

**Comment by chadgh** [comment]
This would be nice. Even with a username:password in the URL, this doesn't work. The error is different though: PermissionError: [Errno 13] Permission denied.

That is with a URL like https://username:password@bitbucket.org/username/project-repo-name

**Comment by pydanny** [comment]
This should be fixed in master thanks to #265. Or the forthcoming 1.0 release. Can you confirm?

**Comment by vfulco** [comment]
Regrettably, life taking me in another direction and no longer actively
exploring. What I saw was well done.  Cheers.

Vince Fulco, CFA, CAIA
612.424.5477 (universal)
vfulco1@gmail.com
twitter: vfulco
wechat (easier than gmail when in China): vfulco

--
"Our job in this lifetime is not to shape ourselves into some ideal we
imagine we ought to be, but to find out who we already are and become it."
-- Steven Pressfield, "The War of Art"
--

**Comment by OksanaShc** [comment]
Will be this bug be fixed? I also met this problem when tryed to use Cookiecutter from python script with some private BB repo.

**Comment by pydanny** [comment]
@OksanaShc Hopefully we'll have funding soon and can start closing out issues that don't impact our professional work. For now, none of us core maintainers can find the free time to fix an issue that isn't directly impacting our own professional work.

Considering no one has this problem on GitHub or GitLab private repos, maybe this is on BitBucket?

**Comment by OksanaShc** [comment]
Thanks for reply.
Frankly speaking, I didn't investigate it because I use only BitBucket for professional work.
But - I found workaround:
cookiecutter('https://%s:%s@bitbucket.org/some_project.git' % (git_username, git_pass)

So to clone repository user just need to put password in link. For the first time I just missed that param 'password' is for extracting zip files, not for cloning repo.

**Comment by insspb** [comment]
I think this is fixed in old times, I do not have bitbucket and cannot test it. Please open new issue if problem still exist.
