### ISSUE TITLE
Hooks are a security concern

### ISSUE THREAD

**Issue by jhermann** [cookiecutter/cookiecutter#429]
Executing the hooks means I trust the template source with anything reachable from my user account – hopefully everyone using templates with hooks does a review beforehand. :see_no_evil: 

I think there should be a `--hooks=abort|skip|ask|trusted` option that defaults to `ask` – many times, users won't know the difference because templates have no hooks, but it will have their backs when it counts (becoming aware they're about to execute abitrary code).

**Comment by hackebrot** [comment]
:+1:

**Comment by hackebrot** [comment]
Hmm...I'm thinking about the options available to the users and the default.

IMHO ``skip`` doesn't make any sense, because the project is probably broken without hooks if set up like that. I am :+1: for ``skip`` and ``ask``. What's your opinion on ``run-anyway``?

Do you want to submit a PR? :smile_cat:

**Comment by hackebrot** [comment]
Hey @jhermann? :grin:

**Comment by audreyr** [comment]
Some thoughts:
* I would call it something like `--hook-verbosity` since it might be good to reserve `--hooks` in case we need to pass in actual hook files or URLs or whatever in the future
* I really like `ask` and `trusted`
* I'm conflicted about `skip`. I could see that it may leave the project broken. I could also see some people using it if they want to look at the hook source and do the trusted actions manually.
* Would `abort` mean that the hook code stops running under particular conditions, e.g. deleting files/dirs outside the project dir, accessing third-party APIs? We'd have to define those conditions.

**Comment by jhermann** [comment]
`abort` was intended to stop the template before it actually writes anything to disk (i.e. "I want no hookish templates"). It's the opposite of `trusted`.

Given that skip is indeed often (but no guaranteed) a problem, another wording would be `--accept-hooks=yes|ask|no`.

**Comment by audreyr** [comment]
I think `--accept-hooks=yes|ask|no` is the clearest.

**Comment by mjscosta** [comment]
Hi, adding the options above are nice, but if you do not trust a template, you should execute it under controlled environment. And take a look at it (hooks), beforehand.

I've searched, for this issue, and came across https://firejail.wordpress.com/,https://l3net.wordpress.com/2015/09/21/firejail-a-security-sandbox-for-mozilla-firefox-part-3/, firejail.

You, can restrict directories access (via while-list), while executing cookiecutter.

**Comment by hackebrot** [comment]
Anyone up for getting this implemented? 😁

**Comment by rgreinho** [comment]
I'm up for the task, and here is a PR we can use to restart the conversation: https://github.com/audreyr/cookiecutter/pull/992.

I do have a use case where I need to ignore the hooks, therefore I would like to have the `skip` option implemented (which is what my PR is for actually).

`--accept-hooks=yes|ask|no` seems to have the consensus, shall I update my PR accordingly?

**Comment by michaeljoseph** [comment]
:+1: to updating #992 to rename `--ignore-hooks` to `--accept-hooks`...

**Comment by rgreinho** [comment]
@michaeljoseph PR #992 updated.

**Comment by paulpach** [comment]
Even if hooks are disabled, people can still put arbitrary code in jinja templates.  Removing the hook does not solve the problem.

A real solution would be sandboxing cookiecutter.  Possible alternatives include:

* Using lxc or docker to run cookicutter in a container. The only problem is that this won't run inside a docker container.

* run cookiecutter in jython.  Use the jvm sandboxing features.  Does cookiecutter run in jython?

* run cookiecutter in ironpython.  use .net sandboxing features. Does cookicutter run in ironpython?

**Comment by insspb** [comment]
@jhermann @paulpach @ssbarnea @michaeljoseph @mjscosta @audreyr 

Thank you all for thoughts and contribution about abort-hooks option. 

At the end:
Discussion about cookiecutter templates security and possible running in safe environment should be done in another place. Issue #1415 created special for this.

`--accept-hooks` pull request #992 is merged to current master and will be available in cookiecutter 2.0

Hooks function at all require more documentation, special issue for tracking all hooks aspects, that should be documented created. #1416 

At this point development is focusing on sorting and cleaning pull requests queue. After queue cleared focus will be switched to documentation rework (Issue #1409) and windows compatibility issues.

Thank you all for you work. Join a party :) We have things to do.

**Comment by KOLANICH** [comment]
>Even if hooks are disabled, people can still put arbitrary code in jinja templates. Removing the hook does not solve the problem.

The real solution would be to get rid of jinja.
