### ISSUE TITLE
Allow for copy_without_render to render output directory name

### ISSUE THREAD

**Issue by codebynumbers** [cookiecutter/cookiecutter#456]
I find it strange that copy_without_render doesn't render the directory name.

An example use case is wanting to copy a templates directory in your project that contains jinja, the directory is copied however it is placed into a folder like '{{cookiecutter.repo_name}}/templates' as opposed to 'someproject/templates'

I understand some people may in fact want this, but maybe an option to to toggle this behavior would welcome.

**Comment by paschembri** [comment]
:+1:
