### ISSUE TITLE
Allow conditional processing of directories and files.

### ISSUE THREAD

**Issue by jcdyer** [cookiecutter/cookiecutter#467]
I would like to be able to skip processing of certain files or directories.  So for instance:

```
- {{cookiecutter.repo_name}}
  + {%if cookiecutter.include_subdir=="true"%}subdir{%endif%}
  | \- file_in_subdir.txt
  \- file1.txt
```

In the case that `include_subdir` is set to `"true"`, this would create the directory and the file inside it.  If `include_subdir` were set to any other value, the directory would not be created, and neither would `file_in_subdir.txt`.  

Currently, the behavior I get from this cookiecutter structure is that if `include_subdir` is not set to `"true"`, the name of the directory is empty, and so `file_in_subdir.txt` gets created in the top directory (as `/repo_name//file_in_subdir.txt`).

Similar functionality should work for individual files as well as directories

This might need an alternative syntax to make it work, in which case it could be a simpler tag `{% fileif condition  "filename" %}`  

Possible names:
- directoryif / fileif ( or dirif)
- compileif (or compile_if)
- renderif
- condition

If this functionality exists, I apologize for the dupe.

**Comment by hackebrot** [comment]
Hi @jcdyer!

Please have a look into [copy-without-render](http://cookiecutter.readthedocs.org/en/latest/advanced_usage.html#copy-without-render) and let me know if this is working for you.

We did not release it just yet. I'll be happy to keep you posted! :bow:

**Comment by jcdyer** [comment]
I don't think that covers the usecase I'm thinking of.  I want template files that are conditionally rendered.  Imagine I want to create a project template that may include certain files depending on the configuration file.  I don't see that copy-without-render provides the ability to decide whether to include the file/directory based on template variables.  Imagine a django project template that asks if the user wants to include celery in their project, and if they do adds a `tasks.py` file with certain defaults set, (or possibly a `tasks` directory with a `__init__.py`.).

**Comment by jcdyer** [comment]
On further consideration, I don't think special syntax is the right way to address this. There are too many odd cases I can think of, like what happens if someone creates a file named `abc{%renderif "true" "def"%}` . I'd rather see the following behavior:

1. If a file name evaluates to an empty string, do not render the file.
2. If a directory name evaluates to an empty string, do not create the directory or render any of the files in the directory.

This seems to follow naturally from the already established rules, and doesn't add any strange cases.
