### ISSUE TITLE
Add Debian package instructions to docs

### ISSUE THREAD

**Issue by audreyr** [cookiecutter/cookiecutter#63]
- Installation
- Usage if anything is different
- General instructions for upgrading to the latest release

**Comment by ivanlyon** [comment]
Debian instructions for latest debian packages posted to docs/installation.rst

I noticed no different usage, but I am a new user and have not explored performance in depth.

**Comment by insspb** [comment]
@audreyr 
Outdated method of distribution. information should be removed, as we have no control on package update. 
I requested additional info in slack, but currently it probably will be removed from docs.
