### ISSUE TITLE
Jinja2 environment settings

### ISSUE THREAD

**Issue by avanderm** [cookiecutter/cookiecutter#704]
Would it be possible to pass arguments to the underlying Jinja2 environment? I would like to activate the `lstrip_blocks` setting in the Jinja2 environment for more convenient whitespace trimming around code blocks. More about the Jinja API here: [Jinja2 API](http://jinja.pocoo.org/docs/dev/api/)

**Comment by luzfcb** [comment]
`{%- -%}` or `{%- %}` or `{% -%}` does not work?


from http://jinja.pocoo.org/docs/dev/templates/#whitespace-control

> You can also strip whitespace in templates by hand. If you add a minus sign (`-`) to the start or end of a block (e.g. a For tag), a comment, or a variable expression, the whitespaces before or after that block will be removed:
> 
> ```python
> {% for item in seq -%}
>     {{ item }}
> {%- endfor %}
> ```
> This will yield all elements without whitespace between them. If seq was a list of numbers from 1 to 9, the output would be 123456789.
> 
> If Line Statements are enabled, they strip leading whitespace automatically up to the beginning of the line.
> 
> By default, Jinja2 also removes trailing newlines. To keep single trailing newlines, configure Jinja to keep_trailing_newline.
> 

> Note
> You must not add whitespace between the tag and the minus sign.
> 
> valid:
> 
> ```python
> {%- if foo -%}...{% endif %}
> ```
> invalid:
> 
> ```python
> {% - if foo - %}...{% endif %}
> ```

**Comment by avanderm** [comment]
Yes, that's what I use at the moment. I do wonder if there's way to pass arguments to the underlying Jinja2 environment in case of other desired behaviour. Also: fixed my link.

**Comment by michaeljoseph** [comment]
@avanderm, you could write

**Comment by pydanny** [comment]
Are there any other use cases for accessing the Cookiecutter Jinja2 Environment? For reference, @avanderm's use case can be addressed with template extensions. If there isn't then I'll go ahead and close this issue.

**Comment by hackebrot** [comment]
It's worth noting that we use more than one environment during project generation. They use slightly different settings.

See **generate.py** and **prompt.py**.

**Comment by cheungnj** [comment]
I'd also like to see this implemented. For my use case, I want to add a custom filter that would be used in several places in my template. I could use a custom extension but if isn't installed then  users wouldn't be able to point cookiecutter at my repo to successfully generate a project. I'd like to avoid having users install this additional extension because I want the template to work with or without it installed on their machines.

**Comment by gtaylor** [comment]
I'd be looking to change jinja's `variable_start_string` and `variable_end_string` to avoid colliding with something I'm templating.

**Comment by insspb** [comment]
> `{%- -%}` or `{%- %}` or `{% -%}` does not work?
> 
> from http://jinja.pocoo.org/docs/dev/templates/#whitespace-control
> 
> > You can also strip whitespace in templates by hand. If you add a minus sign (`-`) to the start or end of a block (e.g. a [For](http://jinja.pocoo.org/docs/dev/templates/#for-loop) tag), a comment, or a variable expression, the whitespaces before or after that block will be removed:
> > ```python
> > {% for item in seq -%}
> >     {{ item }}
> > {%- endfor %}
> > ```
> > 
> > 
> > This will yield all elements without whitespace between them. If _seq_ was a list of numbers from `1` to `9`, the output would be `123456789`.
> > If [Line Statements](http://jinja.pocoo.org/docs/dev/templates/#line-statements) are enabled, they strip leading whitespace automatically up to the beginning of the line.
> > By default, Jinja2 also removes trailing newlines. To keep single trailing newlines, configure Jinja to _keep_trailing_newline_.
> > Note
> > You must not add whitespace between the tag and the minus sign.
> > valid:
> > ```python
> > {%- if foo -%}...{% endif %}
> > ```
> > 
> > 
> > invalid:
> > ```python
> > {% - if foo - %}...{% endif %}
> > ```

This is real pain :)

**Comment by insspb** [comment]
@avanderm @pydanny @gtaylor @cheungnj 
PR #1419 just merged in current master, and will be released in Cookiecutter 2.0. 
At this time you can test it with many other features, by installing cookiecutter from source.

Example:

```
'_jinja2_env_vars': {'lstrip_blocks': True, 'trim_blocks': True},
```

**Comment by ramnes** [comment]
Wow, three years later! What a personal record. Thank you @insspb, I didn't have any hope left for this PR. And I could have done the work also, you just had to ask. 😉

**Comment by insspb** [comment]
@ramnes for some time this project was not maintained. but when you contribute to open source you contribution is used. And I am sure that you patch was used by folks with same problem in custom cookiecutter versions.

But at the end of the day it is only merge to master. Currently master has several new features with `_settings`, but all of them, including this one, should be documented first. Before release. So if you write some docs it will be great!

Thank you.

**Comment by bittner** [comment]
@ramnes I would be interested in this PR. Specifically the white-space control is something that has bothered me from the beginning when I started using Cookiecutter aka Jinja2 (though I now have such much painful experience with the `-` hyphen magic that it's almost scary, and I'd have to do huge refactorings to remove that visual clutter from my templates).

I have an additional requirement myself: Add a custom filter, e.g. the [difference](https://docs.ansible.com/ansible/latest/user_guide/playbooks_templating.html) filter available in Ansible ([source code](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/mathstuff.py#L98-L104)). According to folks on Jinja's "Pallets Projects" Discord server this should be some straight-forward task to do:

> **tachyondecay (she/her)** Today at 6:52 PM
> You could copy the filter code (or code it yourself) and inject it into your Jinja env

Any chance we can get that into Cookiecutter? Or is that possible to do somehow in the [`pre_gen_project` hook](https://cookiecutter.readthedocs.io/en/latest/advanced/hooks.html)?

**Comment by vkottler** [comment]
> At this time you can test it with many other features, by installing cookiecutter from source.

...

> [May 30, 2020](https://github.com/cookiecutter/cookiecutter/issues/704#issuecomment-636328527)

Wot. Why is no one uploading a new package to PyPI? We should all fork our own version of this? What good is a source install if you want to actually distribute templates / instruct end users to use cookiecutters..
