### ISSUE TITLE
Catch up on missing historical items

### ISSUE THREAD

**Issue by pydanny** [cookiecutter/cookiecutter#709]
- Cookiecutter version: Master
### Description:

There have been a few times in the past few months when pull requests were merged in that they were not tracked in https://github.com/audreyr/cookiecutter/blob/master/HISTORY.rst. It would be good if someone could go through the commit list and ensure that everything there matches the history.

**Comment by Kashyap12** [comment]
Hi Can I take this? @pydanny

**Comment by hackebrot** [comment]
Hey @Kashyap12! I'm sure @pydanny is happy with you working on this! Look forward to your PR 👍

**Comment by hackebrot** [comment]
What's the status on this?

**Comment by Nythiennzo** [comment]
Please have a look at #1015 
It's my first time commenting on an issue.

**Comment by kianmehrabani** [comment]
Does this issue still need addressing? I see that #1110, #1181, and #1183 are not in the history but it seems that #1181 is the one with nontrivial changes I think.

**Comment by insspb** [comment]
Already fixed.
