### ISSUE TITLE
Possible solution for documentation re Windows

### ISSUE THREAD

**Issue by BruceEckel** [cookiecutter/cookiecutter#733]
Windows 10 will be adding a fully-integrated Linux shell (from Ubuntu) this summer, which solves that problem (and that may be enough if you're OK saying to use Windows 10).

For those who don't have that, don't want to enable it, or are using an earlier version of Windows:
- http://unxutils.sourceforge.net/ (almost all Unix commands, but they run under the normal windows Command window)

Once that is installed, the commands in the docs work for Windows, with the exception of forward vs. backslashes.

**Comment by audreyr** [comment]
If someone could integrate this into the docs, that would be a big help 👍

**Comment by Nythiennzo** [comment]
Please have look at #1016  
It's one of my first times commenting on an issue.

**Comment by leggettc18** [comment]
That pull request has been merged.... shouldn't this issue be closed then?

**Comment by kishan3** [comment]
Hi @audreyr Can this be closed?
