### ISSUE TITLE
Run pep257 on each file to improve docstrings

### ISSUE THREAD

**Issue by audreyr** [cookiecutter/cookiecutter#742]
How to do this:
1. `pip install pep257`
2. Run it on a single file to see what needs to be improved: `pep257 cookiecutter/generate.py`
3. Fix as much as you can in the file. Whatever you can't fix, don't worry about fixing.
4. Submit a pull request (1 file per pull request for pep257 fixes, please)

**Comment by michaeljoseph** [comment]
This is now [pydocstyle](https://github.com/PyCQA/pydocstyle).
Once we have clean docstrings, I'd suggest adding flake8 support for this via https://gitlab.com/pycqa/flake8-docstrings.

**Comment by staranjeet** [comment]
@audreyr @michaeljoseph : Submitted a PR #779  for this

**Comment by talaniz** [comment]
Hi, I'm getting ready to make my first pull request, I just made some changes to doc strings on prompt.py. I went run the tox tests as shown in the contribution section and received some errors. I was able to paste some of those errors here: http://pastebin.com/yw07RJrp. I was wondering if this was something to be concerned with or if I need to possibly change something in my environment to get them to pass? I followed the instructions on requirement installations and didn't want to haphazardly setup a pull request if everything wasn't passing...

**Comment by hackebrot** [comment]
Hi @talaniz,

I'm happy to hear that you are about to open your first pull request 👍 

We use the click library for cookiecutter and for Python 3 it requires a Unicode locale to be exported, see [click docs](http://click.pocoo.org/5/python3/#python-3-surrogate-handling). Can you please try again with the environment variables set?

```
# encoding
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by talaniz** [comment]
Hello @hackebrot, 

   Thanks for the follow up. I was able to get it working. For some reason, my IDS console threw the errors, but my terminal didn't have any issues running tests. I'm getting an `InterpreterNotFound` error identical to this [issue](https://github.com/audreyr/cookiecutter/issues/404), I'm assuming this is ok as the issue was closed. I'm going to review my work one more time today and submit my pull request.

**Comment by mandeep** [comment]
Is there a checklist of all the files that need to be run against pydocstyle?

**Comment by meahow** [comment]
Looks like these files in the cookiecutter directory still have some pydocstyle issues:
```
cookiecutter/extensions.py
cookiecutter/__init__.py
cookiecutter/log.py
cookiecutter/main.py
cookiecutter/prompt.py
cookiecutter/replay.py
cookiecutter/utils.py
```

**Comment by terryjbates** [comment]
I will withdraw this PR. I am done with contributing to this project.

**Comment by wrongsyntax** [comment]
Are there still any files which need pep257 run on them?
