### ISSUE TITLE
Using cookiecutter to scaffold new elements of a project

### ISSUE THREAD

**Issue by kespindler** [cookiecutter/cookiecutter#785]
It doesn't seem like this is explicitly supported in cookiecutter, but I'm wondering about using cookiecutter to scaffold new elements of a project, something like the following:

```
---project/.cookiecutterrc
{"template": "my-flask-template", "project_name": "my-amazing-app"}
```

Then run

```
cookiecutter AlchemyModel User
```

And you get a new `project/app/models/user.py`. Are there others using cookiecutter like this, or have examples, or is there interest in such a feature?

**Comment by hackebrot** [comment]
Hi @kespindler! 👋 

Thank you for opening this card. I'm afraid I don't quite follow how this could be done with **jinja2** templates and the current version of cookiecutter.

How does above JSON relate to the cookiecutter invocation?

**Comment by kespindler** [comment]
The idea is that even after a project has been created, you could create new files using the same config parameters as the root project. Rails and Yeoman have similar features.

**Comment by bittner** [comment]
I think that needs further explanation.

Would the "new elements of a project" be elements that were added to the cookiecutter (template) _after_ the project had been created? Or are you aiming at scaffolding in the sense of "please create a model in my app" (as Rails does, ATMHO)?

If it's the latter it wouldn't make much sense in the context of this project, as `cookiecutter` is promoted as technology agnostic project template generator(or so). If it's something else that can be useful can you explain it more in detail with a specific, in-depth example? Maybe you even have links to the Yeoman docs to make everyone understand the idea better?

**Comment by insspb** [comment]
No feedback, outdated.
