### ISSUE TITLE
User's JSON parse error causes ugly Python exception

### ISSUE THREAD

**Issue by mlabbe** [cookiecutter/cookiecutter#809]
- Cookiecutter version: 1.4.0
- Template project url: all
- Python version: 3.5.2
- Operating System: Windows 10
### Description:
1. Create a subtly malformed .json file in a project directory
2. Run cookiecutter on that project
3. Observe your eyes glazing over as a huge python exception comes out of it.

Expected results: Succinct user facing error message with descriptive parse error.

**Comment by hackebrot** [comment]
Hi @mlabbe! 👋 

Would you mind creating a patch for this?

**Comment by simobasso** [comment]
closed with https://github.com/cookiecutter/cookiecutter/pull/1468 🎉
