### ISSUE TITLE
Provide guarantees of CWD in hook scripts

### ISSUE THREAD

**Issue by mlabbe** [cookiecutter/cookiecutter#811]
- Cookiecutter version:1.4.0
- Template project url:
- Python version:all
- Operating System:Windows 10
### Description:

What guarantees are there that the CWD for post hook scripts will be root directory of the generated project in future revisions? I could not find this anywhere in the documentation.  This is important to me because I am recursively pruning subdirs in the generated project based on template parameters.  I do not want to accidentally destroy an operating system path.

expected results: post scripts are guaranteed to, in the future, run as they do now, from the CWD of the generated project.

**Comment by insspb** [comment]
No guarantee.
