### ISSUE TITLE
Is there inheritance (or a similar concept) to override behavior of a cookiecutter?

### ISSUE THREAD

**Issue by bittner** [cookiecutter/cookiecutter#818]
- Cookiecutter version: _latest_
- Template project url: e.g. https://github.com/pydanny/cookiecutter-django
- Python version: _any_ (preferably Python 3.4, 3.5)
- Operating System: Ubuntu Linux
### Motivation

I'm looking at cookiecutters like [cookiecutter-django](https://github.com/pydanny/cookiecutter-django), and I think that I may want to add, remove or change some specific implementation details. Specifically, such details that may have difficulties to land in the cookiecutter's repository as accepted PRs (e.g. because there are opinionated changes, implementation choices that cause "religious war" discussions, and the like).

I wouldn't want to do a fork of those projects just to have my own flavor, because that obviously has disadvantages (e.g. keeping up with improvements in the original repository, etc.).
### Question

Is there something like inheritance (or some other concept) in `cookiecutter` that would allow **overriding specific behavior/features** of a cookiecutter? What would be the recommended approach for such a situation?
1. Generate the project first (with my own version of a cookiecutter that runs `cookiecutter <repo-url>`internally), and
2.  then adapt the pieces of the generated result (`sed` / search and replace / etc.)?
### Note

I've seen issue #409. I don't want to go into discussions about this idea. It's really that I want to understand what is the creators' idea and/or suggested approach for any such situations.

**Comment by hackebrot** [comment]
Hi @bittner! 👋 

There are no plans at this point to implement something like *template inheritance*, as far as I can tell.

**Comment by simobasso** [comment]
Hi there!

Just opened #1485 that implements templates inheritance using jinja's templating inheritance as described in #1484.

If you are interested please have a look! 😊
