### ISSUE TITLE
default choice for list of options in .cookiecutterrc

### ISSUE THREAD

**Issue by feigaoxyz** [cookiecutter/cookiecutter#830]
Currently for a list of options, the default choice is [hard-coded to be the first one](https://github.com/audreyr/cookiecutter/blob/master/cookiecutter/prompt.py#L71).

I wonder if this is a design decision or we should fix it?

**Comment by hackebrot** [comment]
Hi @feigaoxyz! 👋 

This is indeed a design decision as the current context format does not allow extended variable information. What would be the preferred solution for you?

Happy to discuss here! 👍

**Comment by hackebrot** [comment]
See #848
