### ISSUE TITLE
git pull instead of re-clone

### ISSUE THREAD

**Issue by ryanolson** [cookiecutter/cookiecutter#846]
* Cookiecutter version: latest
* Template project url: n/a
* Python version: n/a
* Operating System: n/a

### Description:

Instead of deleting a git repo that has already been pulled, it seems most logical that we should perform a pull instead of deleting the repo and recloning.

https://github.com/audreyr/cookiecutter/blob/e041f215e5def801529a67af03f0bcf283af38aa/cookiecutter/vcs.py#L28

If the pull fails, then a wipe and reload is in order.

**Comment by pydanny** [comment]
Interesting idea, certainly could speed things up with Cookiecutter Django.

The downside is the additional complexity for Cookiecutter.

**Comment by ryanolson** [comment]
I know you guys don't like to add a lot of external dependencies; however you do require `git` to be installed, perhaps it's not too much to  add [pygit2](https://github.com/libgit2/pygit2) to the set of dependencies.  That greatly simply the `vcs.py` code and make pulling much easier.

**Comment by pydanny** [comment]
Thanks for the other suggestion, but the installation issues across multiple platforms are a show stopper for Cookiecutter integration (http://www.pygit2.org/install.html#libgit2-within-a-virtual-environment)

**Comment by ryanolson** [comment]
Gotcha.  If I have time, I'll see about adding some submodule calls for performing a pull.

**Comment by pydanny** [comment]
Umm... Pygit has dependency issues that are way too broad for the Cookiecutter maintainers to cover. Any simplification of code that it will provide will be offset many times over by users across many platforms asking for help with libgit installation help.

**Comment by kurtmckee** [comment]
It may be possible to implement this using dulwich nowadays, but this represents additional complexity for cookiecutter, and it's outside of what the team can write and maintain at this time.

I'm closing this ticket due to the feature's complexity and maintenance effort.
