### ISSUE TITLE
Add support for secure password input

### ISSUE THREAD

**Issue by NathanUrwin** [cookiecutter/cookiecutter#853]
I'm not sure how it could be implemented, but the option to choose between `raw_input` and `getpass.getpass` for secure password input would be an awesome feature.

Thanks in advance for your time!

EDIT: Maybe something along the lines of...
```
{
    "username": {
        "default": "tuxredux",
        "_input": "raw_input"
        },
    "password": {
        "default": "",
         "_input": "getpass.getpass"
        }
}
```

**Comment by hackebrot** [comment]
Hi @tuxredux! 👋 

Thank you for suggesting this feature.

It would be something that we could add with #848. I have updated the PR with an example for hidden inputs.

**Comment by tuxredux** [comment]
Hey @hackebrot, thanks for the reply!

The new proposed context format looks AMAZING and VERY powerful! :D

I would definitely sponsor the new feature if I wasn't a one-man startup with little to zero funds :(

Hopefully, someone will though. Keep up the great work!

**Comment by hackebrot** [comment]
Thank you for your kind words @tuxredux! 🙇

**Comment by kurtmckee** [comment]
I'm closing this issue due to its age, and to focus developer/maintainer efforts. This can only be supported by other work (like a new config file format) that has not yet happened.
