### ISSUE TITLE
Support symlinks on Windows with Python < 3.2

### ISSUE THREAD

**Issue by pjbull** [cookiecutter/cookiecutter#947]
Cookiecutter currently raises `NoSymlinksOnWindowsPythonBefore32` when it finds a symlink on Windows systems with Python < 3.2.

For context, see:
 - [Original Issue](https://github.com/audreyr/cookiecutter/issues/865)
 - [Rejected pull request with custom Win32 code](https://github.com/audreyr/cookiecutter/pull/868)
 - [Accepted pull request for symlinks with `NoSymlinksOnWindowsPythonBefore32`](https://github.com/audreyr/cookiecutter/pull/934)

It's possible that we can use `jaraco.windows` to patch the `os` module on these systems, but that was failing to pass the tests with the `skipif` removed.

Here is where we currently patch to raise the error:
 - [Where we currently patch islink]()
 - [`jaraco.windows` patching calls for `os` module](https://github.com/jaraco/jaraco.windows#installation)

Here is where we test symlinks, and this test should pass with the `skipif` removed:

**Comment by insspb** [comment]
we are not supporting Py 3.2 anymore
