### ISSUE TITLE
mixed hooks (both sh and py) in the same project

### ISSUE THREAD

**Issue by milonimrod** [cookiecutter/cookiecutter#973]
* Cookiecutter version: 1.5.1
* Python version: 2.7.13
* Operating System: Linux

### Description:

I was wandering if there is an option to add the ability to have both _sh_ and _py_ hook scripts in the package. It seems very straight forward to implement.

Thank you,
Nimrod

**Comment by milonimrod** [comment]
I've created a pull request about it #974

**Comment by michaeljoseph** [comment]
I'm not entirely convinced of the generic utility of this functionality?

Could you give us an example use-case?

**Comment by milonimrod** [comment]
Yes, I have an example (which is the reason I found the need). In our fork we wanted to run after each creation:
1. Git initiation and adding of files
2. Registration of the project in internal remote git server
3. Run a few calls to several APIs
4. Unit a connection to docker

Some of the above are suited for python scripts and some are for bash scripts. So to make the development and maintenance easier we looked for the above feature.

**Comment by michaeljoseph** [comment]
I'm still not convinced that we should be adding this as a core feature for a somewhat minor (IMO) convenience.
🤔 @hackebrot @pydanny @audreyr ?

**Comment by michaeljoseph** [comment]
@milonimrod #824 may be a solution to your problem by allowing some organisation of utility hook code.

**Comment by milonimrod** [comment]
@michaeljoseph I'm not sure how #824 may help as it still require that i'll implement either a python script or a bash script. then I'll need to orchestrate all the calls.

The only caveat that I see in my approach is that it is not clear which script runs first. I would suggest to extend the hooks scripting into an approach like linux services. I mean that the name of the hook will determine the order. For example: 01_pre_gen_project.py, 02_pre_gen_project.sh, 03_pre_gen_project.py

**Comment by lszyba1** [comment]
Couldn't you add your shell code to post_gen
1. Generate initial template
2. Run your SH script
3. Use examples below to modify the already generated templates from part 1 with additional changes after shell returned the results
http://lucasmanual.com/blog/cookiecutter-modify-context-in-post_gen_project-py/
Lucas

**Comment by milonimrod** [comment]
Hi @lszyba1,
I think that solving using 1 & 2 is too and requires the user to have long and cluttered scripts. 3 seems very useful for many tasks but I don't think this is a good approach. As I see it, it can help organize the hooks in a tidy manner

**Comment by yggdr** [comment]
Some things are more easily done in a shell script, others in e.g. python. Moving stuff around in the filesystem, echoing into files, etc. is doable in python, sure, but feels much more natural in shell.

So having multiple hook files in different languages would be nice. I for one just figured out that this feature is missing from cookiecutter, despite the doc string of `find_hook` stating that it returns "a dict of **all** hook scripts provided.". So I now can either rewrite shell script in python (which I don't want), or rewrite the stuff I do in python in shell (which I _really_ don't want), or do some hacks to the shell script can find and run the python hook and run it.

So I'd be +1 on a patch that runs all hook files it finds, even if coockiecutter makes no guarantee about the order.

**Comment by JanBednarik** [comment]
+1 for this feature. It's very inconvenient that cookiecutter silently skips `.sh` hooks when `.py` are added.

**Comment by jaklan** [comment]
> +1 for this feature. It's very inconvenient that cookiecutter silently skips `.sh` hooks when `.py` are added.

That's interesting, in my case `post_gen_project.sh` is preferred over "post_gen_project.py".
But in general - also +1, it's really annoying.

**Comment by insspb** [comment]
@JanBednarik @jaklan @yggdr @milonimrod The #974 implementation is added in current `master` and may be released in `cookiecutter 2.0`. I have some concerns about all hook module functional and compatibility, and the final decision will be made on `cookiecutter` 2.0 release.
