### ISSUE TITLE
Add CODEOWNERS to Project

### ISSUE THREAD

**Issue by theodesp** [cookiecutter/cookiecutter#979]
* Cookiecutter version: latest
* Template project url:
* Python version: 3.6
* Operating System: MacOs Sierra

### Description:

We need to add a CODEOWNERS file 
https://github.com/blog/2392-introducing-code-owners
to simplify code reviews on PULL REQUESTS

**Comment by hackebrot** [comment]
Hi @theodesp! 👋 

Thanks for the suggestion.

There are only a handful maintainers for Cookiecutter and no part of this project is *owned* by a particular person. I'd rather not send emails automatically to maintainers and request a review from them. If they decide to watch this repo they will get notified anyways.

From [Code Owners blogpost](https://github.com/blog/2392-introducing-code-owners)

> With that in place, code owners will automatically be requested for review whenever a pull request touches the files they own.

**Comment by insspb** [comment]
Declined
